package com.example.mediaproducer;

import io.mcpmesh.MeshAgent;
import io.mcpmesh.MeshTool;
import io.mcpmesh.Param;
import io.mcpmesh.spring.media.MediaStore;
import io.mcpmesh.spring.media.MeshMedia;
import io.modelcontextprotocol.spec.McpSchema.ResourceLink;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.CRC32;
import java.util.zip.Deflater;
import java.util.zip.DeflaterOutputStream;

/**
 * MCP Mesh media producer agent.
 *
 * <p>Demonstrates generating media content (markdown, SVG, PNG) and returning
 * {@code resource_link} content types via the mesh media API. This is the Java
 * equivalent of the Python {@code media_producer.py} example.
 *
 * <h2>Tools</h2>
 * <ul>
 *   <li>{@code generate_report} — creates a markdown report and returns a ResourceLink</li>
 *   <li>{@code generate_chart} — creates an SVG bar chart and returns a ResourceLink</li>
 *   <li>{@code get_sample_image} — creates a minimal PNG image and returns a ResourceLink</li>
 * </ul>
 *
 * <h2>Running</h2>
 * <pre>
 * meshctl start --registry-only
 * cd examples/java/media-producer-agent
 * mvn spring-boot:run
 *
 * meshctl list -t
 * meshctl call generate_report '{"topic": "AI"}'
 * meshctl call generate_chart '{"data": "Sales:40,Marketing:25"}'
 * meshctl call get_sample_image '{}'
 * </pre>
 */
@MeshAgent(
    name = "media-producer",
    version = "1.0.0",
    description = "Agent that generates media content and returns resource_links",
    port = 9220
)
@SpringBootApplication
public class MediaProducerAgentApplication {

    private static final Logger log = LoggerFactory.getLogger(MediaProducerAgentApplication.class);

    @Autowired
    private MediaStore mediaStore;

    public static void main(String[] args) {
        log.info("Starting Media Producer Agent...");
        SpringApplication.run(MediaProducerAgentApplication.class, args);
    }

    /**
     * Generate a markdown report on a given topic.
     *
     * @param topic The topic for the report
     * @return ResourceLink pointing to the uploaded markdown file
     */
    @MeshTool(
        capability = "report_generator",
        description = "Generates a markdown report on a topic",
        tags = {"media", "report", "markdown", "java"}
    )
    public ResourceLink generateReport(
        @Param(value = "topic", description = "The topic for the report") String topic
    ) {
        if (topic == null || topic.isBlank()) {
            topic = "AI";
        }
        log.info("Generating report on: {}", topic);

        String slug = topic.toLowerCase().replace(" ", "_");
        String content = String.format("""
            # Report: %s

            ## Executive Summary

            This is an auto-generated report on **%s** produced by the media-producer agent.

            ## Key Findings

            1. %s continues to evolve rapidly across multiple domains.
            2. Adoption rates have increased significantly in the past year.
            3. Integration with existing systems remains a priority.

            ## Recommendations

            - Invest in foundational research for %s.
            - Develop clear governance frameworks.
            - Monitor emerging trends and adjust strategy accordingly.

            ---
            *Generated by media-producer-java agent*
            """, topic, topic, topic, topic);

        byte[] data = content.getBytes(StandardCharsets.UTF_8);
        String filename = "report_" + slug + ".md";
        String uri = mediaStore.upload(data, filename, "text/markdown");

        log.info("Uploaded report: {} ({} bytes)", uri, data.length);

        return MeshMedia.mediaResult(
            uri, "Report: " + topic, "text/markdown",
            "Markdown report on " + topic, (long) data.length
        );
    }

    /**
     * Generate an SVG bar chart from label:value pairs.
     *
     * @param data Comma-separated Label:Value pairs (e.g., "Sales:40,Marketing:25")
     * @return ResourceLink pointing to the uploaded SVG file
     */
    @MeshTool(
        capability = "chart_generator",
        description = "Generates an SVG bar chart from data",
        tags = {"media", "chart", "svg", "java"}
    )
    public ResourceLink generateChart(
        @Param(value = "data", description = "Comma-separated Label:Value pairs") String data
    ) {
        if (data == null || data.isBlank()) {
            data = "Sales:40,Marketing:25,Engineering:60,Support:15";
        }
        log.info("Generating chart from: {}", data);

        List<String[]> pairs = new ArrayList<>();
        for (String item : data.split(",")) {
            String[] parts = item.trim().split(":");
            if (parts.length == 2) {
                try {
                    Double.parseDouble(parts[1].trim());
                    pairs.add(new String[]{parts[0].trim(), parts[1].trim()});
                } catch (NumberFormatException ignored) {
                }
            }
        }

        if (pairs.isEmpty()) {
            pairs.add(new String[]{"A", "30"});
            pairs.add(new String[]{"B", "50"});
            pairs.add(new String[]{"C", "20"});
        }

        double maxVal = pairs.stream()
            .mapToDouble(p -> Double.parseDouble(p[1]))
            .max()
            .orElse(1.0);

        int barWidth = 60;
        int gap = 20;
        int chartHeight = 200;
        int marginBottom = 40;
        int marginTop = 20;
        int marginLeft = 10;
        int totalWidth = marginLeft + pairs.size() * (barWidth + gap) + gap;
        int totalHeight = chartHeight + marginBottom + marginTop;

        String[] colors = {"#4e79a7", "#f28e2b", "#e15759", "#76b7b2", "#59a14f", "#edc948", "#b07aa1", "#ff9da7"};

        StringBuilder barsSvg = new StringBuilder();
        for (int i = 0; i < pairs.size(); i++) {
            String label = pairs.get(i)[0];
            double value = Double.parseDouble(pairs.get(i)[1]);
            double barHeight = maxVal > 0 ? (value / maxVal) * chartHeight : 0;
            int x = marginLeft + gap + i * (barWidth + gap);
            double y = marginTop + chartHeight - barHeight;
            String color = colors[i % colors.length];

            barsSvg.append(String.format(
                "  <rect x=\"%d\" y=\"%.0f\" width=\"%d\" height=\"%.0f\" fill=\"%s\" rx=\"4\"/>\n",
                x, y, barWidth, barHeight, color));
            barsSvg.append(String.format(
                "  <text x=\"%d\" y=\"%d\" text-anchor=\"middle\" font-size=\"12\" font-family=\"sans-serif\" fill=\"#333\">%s</text>\n",
                x + barWidth / 2, marginTop + chartHeight + 16, label));
            barsSvg.append(String.format(
                "  <text x=\"%d\" y=\"%.0f\" text-anchor=\"middle\" font-size=\"11\" font-family=\"sans-serif\" fill=\"#555\">%s</text>\n",
                x + barWidth / 2, y - 5, formatNumber(value)));
        }

        String svg = String.format("""
            <?xml version="1.0" encoding="UTF-8"?>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d">
              <rect width="100%%" height="100%%" fill="#fafafa" rx="8"/>
              <line x1="%d" y1="%d" x2="%d" y2="%d" stroke="#ccc" stroke-width="1"/>
            %s</svg>
            """,
            totalWidth, totalHeight, totalWidth, totalHeight,
            marginLeft + gap, marginTop + chartHeight, totalWidth - gap, marginTop + chartHeight,
            barsSvg);

        byte[] svgBytes = svg.getBytes(StandardCharsets.UTF_8);
        String uri = mediaStore.upload(svgBytes, "chart.svg", "image/svg+xml");

        log.info("Uploaded chart: {} ({} bytes)", uri, svgBytes.length);

        return MeshMedia.mediaResult(
            uri, "Bar Chart", "image/svg+xml",
            "SVG bar chart with " + pairs.size() + " data points", (long) svgBytes.length
        );
    }

    /**
     * Create and return a minimal valid PNG image (a small blue square).
     *
     * @return ResourceLink pointing to the uploaded PNG file
     */
    @MeshTool(
        capability = "image_generator",
        description = "Returns a sample PNG image",
        tags = {"media", "image", "png", "java"}
    )
    public ResourceLink getSampleImage() {
        log.info("Generating sample PNG image");

        byte[] pngBytes = buildMinimalPng(2, 2, new byte[]{0x33, 0x66, (byte) 0xCC});

        String uri = mediaStore.upload(pngBytes, "sample_image.png", "image/png");

        log.info("Uploaded PNG: {} ({} bytes)", uri, pngBytes.length);

        return MeshMedia.mediaResult(
            uri, "Sample Image", "image/png",
            "A small 2x2 blue PNG image", (long) pngBytes.length
        );
    }

    /**
     * Build a minimal valid PNG file with uniform pixel color.
     * Uses raw byte manipulation — no ImageIO or external libraries.
     */
    static byte[] buildMinimalPng(int width, int height, byte[] rgb) {
        // Build raw image data: each row starts with filter byte 0 (None), then RGB pixels
        byte[] rawRows = new byte[height * (1 + width * 3)];
        int offset = 0;
        for (int row = 0; row < height; row++) {
            rawRows[offset++] = 0; // filter byte: None
            for (int col = 0; col < width; col++) {
                rawRows[offset++] = rgb[0];
                rawRows[offset++] = rgb[1];
                rawRows[offset++] = rgb[2];
            }
        }

        // Compress with zlib/deflate
        byte[] compressed;
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            DeflaterOutputStream dos = new DeflaterOutputStream(baos, new Deflater());
            dos.write(rawRows);
            dos.finish();
            dos.close();
            compressed = baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to compress PNG data", e);
        }

        // PNG signature
        byte[] signature = {(byte) 0x89, 'P', 'N', 'G', '\r', '\n', 0x1A, '\n'};

        // IHDR chunk data: width(4) + height(4) + bitDepth(1) + colorType(1) + compression(1) + filter(1) + interlace(1)
        byte[] ihdrData = new byte[13];
        writeInt(ihdrData, 0, width);
        writeInt(ihdrData, 4, height);
        ihdrData[8] = 8;  // bit depth
        ihdrData[9] = 2;  // color type: RGB
        ihdrData[10] = 0; // compression
        ihdrData[11] = 0; // filter
        ihdrData[12] = 0; // interlace

        byte[] ihdr = buildChunk("IHDR", ihdrData);
        byte[] idat = buildChunk("IDAT", compressed);
        byte[] iend = buildChunk("IEND", new byte[0]);

        // Assemble full PNG
        ByteArrayOutputStream png = new ByteArrayOutputStream();
        try {
            png.write(signature);
            png.write(ihdr);
            png.write(idat);
            png.write(iend);
        } catch (Exception e) {
            throw new RuntimeException("Failed to assemble PNG", e);
        }
        return png.toByteArray();
    }

    private static byte[] buildChunk(String type, byte[] data) {
        byte[] typeBytes = type.getBytes(StandardCharsets.US_ASCII);
        byte[] chunk = new byte[4 + 4 + data.length + 4]; // length + type + data + crc

        // Length
        writeInt(chunk, 0, data.length);

        // Type
        System.arraycopy(typeBytes, 0, chunk, 4, 4);

        // Data
        System.arraycopy(data, 0, chunk, 8, data.length);

        // CRC over type + data
        CRC32 crc = new CRC32();
        crc.update(typeBytes);
        crc.update(data);
        writeInt(chunk, 8 + data.length, (int) crc.getValue());

        return chunk;
    }

    private static void writeInt(byte[] buf, int offset, int value) {
        buf[offset] = (byte) (value >> 24);
        buf[offset + 1] = (byte) (value >> 16);
        buf[offset + 2] = (byte) (value >> 8);
        buf[offset + 3] = (byte) value;
    }

    private static String formatNumber(double value) {
        if (value == (long) value) {
            return String.valueOf((long) value);
        }
        return String.valueOf(value);
    }
}
