# Chart Releaser configuration
# See: https://github.com/helm/chart-releaser#configuration

# Release name template
release-name-template: "{{ .Name }}-{{ .Version }}"

# Skip packaging if version already exists
skip-existing: true

# Generate release notes from CHANGELOG
generate-release-notes: true

# Mark prerelease versions appropriately
mark-as-latest: true
