apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-mesh-enhanced-fastmcp-agent
  namespace: mcp-mesh
  labels:
    app.kubernetes.io/name: mcp-mesh-enhanced-fastmcp-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/version: "2.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-mesh-enhanced-fastmcp-agent
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-mesh-enhanced-fastmcp-agent
        app.kubernetes.io/component: agent
        app.kubernetes.io/version: "2.0.0"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: enhanced-fastmcp-agent
          image: mcpmesh/python-runtime:0.5
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/agent.py"]
          ports:
            - name: http
              containerPort: 9094
              protocol: TCP
          env:
            # Registry connection - configurable for federated networks
            - name: MCP_MESH_REGISTRY_HOST
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: REGISTRY_HOST
            - name: MCP_MESH_REGISTRY_PORT
              valueFrom:
                configMapKeyRef:
                  name: mcp-agent-config
                  key: REGISTRY_PORT
            # HTTP server binding - bind to all interfaces
            - name: HOST
              value: "0.0.0.0"
            # Kubernetes service discovery - auto-detect from labels
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # Fallback pod IP for backward compatibility
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MCP_MESH_AGENT_NAME
              value: "enhanced-fastmcp-service"
            - name: MCP_MESH_HTTP_HOST
              value: "mcp-mesh-enhanced-fastmcp-agent"
            - name: MCP_MESH_HTTP_PORT
              value: "9094"
            # Enhanced agent specific configuration
            - name: AGENT_ID
              value: "enhanced-fastmcp-service"
            # Redis for session storage (Phase 6+)
            - name: REDIS_URL
              value: "redis://mcp-mesh-redis:6379"
          envFrom:
            - configMapRef:
                name: mcp-agent-config
          livenessProbe:
            httpGet:
              path: /health
              port: 9094
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9094
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 9094
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: agent-code
              mountPath: /app/agent.py
              subPath: enhanced_fastmcp_agent.py
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true

      volumes:
        - name: agent-code
          configMap:
            name: mcp-agent-code

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-mesh-enhanced-fastmcp-agent
  namespace: mcp-mesh
  labels:
    app.kubernetes.io/name: mcp-mesh-enhanced-fastmcp-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/version: "2.0.0"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9094
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: mcp-mesh-enhanced-fastmcp-agent
    app.kubernetes.io/component: agent
