apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: mcp-mesh
data:
  grafana.ini: |
    # Grafana configuration loaded from observability/grafana/grafana.ini
    # This references the actual config file in the observability directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: mcp-mesh
data:
  # Dashboard files will be mounted from observability/grafana/dashboards/
  # This allows referencing the centralized dashboard configurations
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mcp-mesh
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        editable: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        uid: prometheus
        editable: true