apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: mcp-mesh
data:
  grafana.ini: |
    # Basic configuration
    [server]
    http_port = 3000
    enable_gzip = true

    [security]
    admin_password = admin

    [users]
    allow_sign_up = false

    [plugins]
    enable_alpha = false
    install_plugins = grafana-piechart-panel

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [dashboards]
    default_home_dashboard_path = /etc/grafana/dashboards/mcp-mesh-overview.json

    [feature_toggles]
    enable = traceqlEditor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mcp-mesh
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      uid: tempo
      editable: true
      isDefault: false
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      uid: prometheus
      editable: true
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: mcp-mesh
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'mcp-mesh'
      orgId: 1
      folder: 'MCP Mesh'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /etc/grafana/dashboards
