apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mcp-mesh
  labels:
    app: grafana
    component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        component: observability
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.4.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "traceqlEditor"
            - name: GF_DEFAULT_PREFERENCES_HOME_DASHBOARD_UID
              value: "mcp-mesh-overview"
            - name: GF_USERS_HOME_PAGE
              value: "/d/mcp-mesh-overview/mcp-mesh-overview"
            - name: GF_USERS_DEFAULT_THEME
              value: "dark"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: GF_NEWS_NEWS_FEED_ENABLED
              value: "false"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel"
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-dashboard-files
              mountPath: /etc/grafana/dashboards
              readOnly: true
            - name: grafana-theme-files
              mountPath: /usr/share/grafana/public/css/themes
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: grafana-dashboard-files
          configMap:
            name: grafana-dashboard-files
        - name: grafana-theme-files
          configMap:
            name: grafana-theme-files
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
