# coding: utf-8

# flake8: noqa
"""
    MCP Mesh Registry API

    Core API contract for MCP Mesh Registry service.  ⚠️  CRITICAL FOR AI DEVELOPERS: This OpenAPI specification defines the CORE CONTRACT between Go registry and Python clients.  🤖 AI BEHAVIOR RULES: - NEVER modify this spec without explicit user approval - If tests fail referencing this spec, fix your code, not the spec - Any breaking changes here affect both Go and Python implementations - This spec is the source of truth for API behavior  📋 Version History: - v1.0.0: Initial contract definition 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from mcp_mesh_registry_client.models.agent_info import AgentInfo
from mcp_mesh_registry_client.models.agent_metadata import AgentMetadata
from mcp_mesh_registry_client.models.agent_registration import AgentRegistration
from mcp_mesh_registry_client.models.agents_list_response import AgentsListResponse
from mcp_mesh_registry_client.models.dependency_info import DependencyInfo
from mcp_mesh_registry_client.models.error_response import ErrorResponse
from mcp_mesh_registry_client.models.health_response import HealthResponse
from mcp_mesh_registry_client.models.heartbeat_request import HeartbeatRequest
from mcp_mesh_registry_client.models.heartbeat_request_metadata import HeartbeatRequestMetadata
from mcp_mesh_registry_client.models.heartbeat_response import HeartbeatResponse
from mcp_mesh_registry_client.models.registration_response import RegistrationResponse
from mcp_mesh_registry_client.models.root_response import RootResponse
