{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-mesh-grafana.fullname" . }}-config
  labels:
    {{- include "mcp-mesh-grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    # Basic configuration
    [server]
    http_port = 3000
    enable_gzip = true

    [security]
    admin_password = {{ .Values.grafana.config.adminPassword | quote }}

    [users]
    allow_sign_up = {{ .Values.grafana.config.allowSignUp }}

    [plugins]
    enable_alpha = false
    {{- if .Values.grafana.config.installPlugins }}
    install_plugins = {{ .Values.grafana.config.installPlugins }}
    {{- end }}

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/mcp-mesh-overview.json

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-mesh-grafana.fullname" . }}-datasources
  labels:
    {{- include "mcp-mesh-grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- if .Values.grafana.datasources.tempo.enabled }}
    - name: Tempo
      type: tempo
      access: proxy
      url: {{ .Values.grafana.datasources.tempo.url }}
      uid: tempo
      editable: true
      isDefault: false
    {{- end }}
    {{- if .Values.grafana.datasources.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: {{ .Values.grafana.datasources.prometheus.url }}
      uid: prometheus
      editable: true
      isDefault: true
    {{- end }}

---
{{- if .Values.grafana.dashboards.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-mesh-grafana.fullname" . }}-dashboards-config
  labels:
    {{- include "mcp-mesh-grafana.labels" . | nindent 4 }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'mcp-mesh'
      orgId: 1
      folder: 'MCP Mesh'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
{{- end }}
{{- end }}
