{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mcp-mesh-grafana.fullname" . }}-pvc
  labels:
    {{- include "mcp-mesh-grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.grafana.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | quote }}
  {{- if .Values.grafana.persistence.storageClass }}
  {{- if (eq "-" .Values.grafana.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
