// Code generated by ent, DO NOT EDIT.

package job

import (
	"mcp-mesh/src/core/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldID, id))
}

// Capability applies equality check predicate on the "capability" field. It's identical to CapabilityEQ.
func Capability(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCapability, v))
}

// OwnerInstanceID applies equality check predicate on the "owner_instance_id" field. It's identical to OwnerInstanceIDEQ.
func OwnerInstanceID(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldOwnerInstanceID, v))
}

// ClaimEpoch applies equality check predicate on the "claim_epoch" field. It's identical to ClaimEpochEQ.
func ClaimEpoch(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldClaimEpoch, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v float64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProgress, v))
}

// ProgressMessage applies equality check predicate on the "progress_message" field. It's identical to ProgressMessageEQ.
func ProgressMessage(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProgressMessage, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldError, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAttemptCount, v))
}

// MaxRetries applies equality check predicate on the "max_retries" field. It's identical to MaxRetriesEQ.
func MaxRetries(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMaxRetries, v))
}

// MaxDuration applies equality check predicate on the "max_duration" field. It's identical to MaxDurationEQ.
func MaxDuration(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMaxDuration, v))
}

// TotalDeadline applies equality check predicate on the "total_deadline" field. It's identical to TotalDeadlineEQ.
func TotalDeadline(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTotalDeadline, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedBy applies equality check predicate on the "submitted_by" field. It's identical to SubmittedByEQ.
func SubmittedBy(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSubmittedBy, v))
}

// CapabilityEQ applies the EQ predicate on the "capability" field.
func CapabilityEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCapability, v))
}

// CapabilityNEQ applies the NEQ predicate on the "capability" field.
func CapabilityNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCapability, v))
}

// CapabilityIn applies the In predicate on the "capability" field.
func CapabilityIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCapability, vs...))
}

// CapabilityNotIn applies the NotIn predicate on the "capability" field.
func CapabilityNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCapability, vs...))
}

// CapabilityGT applies the GT predicate on the "capability" field.
func CapabilityGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCapability, v))
}

// CapabilityGTE applies the GTE predicate on the "capability" field.
func CapabilityGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCapability, v))
}

// CapabilityLT applies the LT predicate on the "capability" field.
func CapabilityLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCapability, v))
}

// CapabilityLTE applies the LTE predicate on the "capability" field.
func CapabilityLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCapability, v))
}

// CapabilityContains applies the Contains predicate on the "capability" field.
func CapabilityContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldCapability, v))
}

// CapabilityHasPrefix applies the HasPrefix predicate on the "capability" field.
func CapabilityHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldCapability, v))
}

// CapabilityHasSuffix applies the HasSuffix predicate on the "capability" field.
func CapabilityHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldCapability, v))
}

// CapabilityEqualFold applies the EqualFold predicate on the "capability" field.
func CapabilityEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldCapability, v))
}

// CapabilityContainsFold applies the ContainsFold predicate on the "capability" field.
func CapabilityContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldCapability, v))
}

// OwnerInstanceIDEQ applies the EQ predicate on the "owner_instance_id" field.
func OwnerInstanceIDEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDNEQ applies the NEQ predicate on the "owner_instance_id" field.
func OwnerInstanceIDNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDIn applies the In predicate on the "owner_instance_id" field.
func OwnerInstanceIDIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldOwnerInstanceID, vs...))
}

// OwnerInstanceIDNotIn applies the NotIn predicate on the "owner_instance_id" field.
func OwnerInstanceIDNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldOwnerInstanceID, vs...))
}

// OwnerInstanceIDGT applies the GT predicate on the "owner_instance_id" field.
func OwnerInstanceIDGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDGTE applies the GTE predicate on the "owner_instance_id" field.
func OwnerInstanceIDGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDLT applies the LT predicate on the "owner_instance_id" field.
func OwnerInstanceIDLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDLTE applies the LTE predicate on the "owner_instance_id" field.
func OwnerInstanceIDLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDContains applies the Contains predicate on the "owner_instance_id" field.
func OwnerInstanceIDContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDHasPrefix applies the HasPrefix predicate on the "owner_instance_id" field.
func OwnerInstanceIDHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDHasSuffix applies the HasSuffix predicate on the "owner_instance_id" field.
func OwnerInstanceIDHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDIsNil applies the IsNil predicate on the "owner_instance_id" field.
func OwnerInstanceIDIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldOwnerInstanceID))
}

// OwnerInstanceIDNotNil applies the NotNil predicate on the "owner_instance_id" field.
func OwnerInstanceIDNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldOwnerInstanceID))
}

// OwnerInstanceIDEqualFold applies the EqualFold predicate on the "owner_instance_id" field.
func OwnerInstanceIDEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldOwnerInstanceID, v))
}

// OwnerInstanceIDContainsFold applies the ContainsFold predicate on the "owner_instance_id" field.
func OwnerInstanceIDContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldOwnerInstanceID, v))
}

// ClaimEpochEQ applies the EQ predicate on the "claim_epoch" field.
func ClaimEpochEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldClaimEpoch, v))
}

// ClaimEpochNEQ applies the NEQ predicate on the "claim_epoch" field.
func ClaimEpochNEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldClaimEpoch, v))
}

// ClaimEpochIn applies the In predicate on the "claim_epoch" field.
func ClaimEpochIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldClaimEpoch, vs...))
}

// ClaimEpochNotIn applies the NotIn predicate on the "claim_epoch" field.
func ClaimEpochNotIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldClaimEpoch, vs...))
}

// ClaimEpochGT applies the GT predicate on the "claim_epoch" field.
func ClaimEpochGT(v int64) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldClaimEpoch, v))
}

// ClaimEpochGTE applies the GTE predicate on the "claim_epoch" field.
func ClaimEpochGTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldClaimEpoch, v))
}

// ClaimEpochLT applies the LT predicate on the "claim_epoch" field.
func ClaimEpochLT(v int64) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldClaimEpoch, v))
}

// ClaimEpochLTE applies the LTE predicate on the "claim_epoch" field.
func ClaimEpochLTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldClaimEpoch, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v float64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v float64) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...float64) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...float64) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v float64) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v float64) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v float64) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v float64) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldProgress, v))
}

// ProgressIsNil applies the IsNil predicate on the "progress" field.
func ProgressIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldProgress))
}

// ProgressNotNil applies the NotNil predicate on the "progress" field.
func ProgressNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldProgress))
}

// ProgressMessageEQ applies the EQ predicate on the "progress_message" field.
func ProgressMessageEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldProgressMessage, v))
}

// ProgressMessageNEQ applies the NEQ predicate on the "progress_message" field.
func ProgressMessageNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldProgressMessage, v))
}

// ProgressMessageIn applies the In predicate on the "progress_message" field.
func ProgressMessageIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldProgressMessage, vs...))
}

// ProgressMessageNotIn applies the NotIn predicate on the "progress_message" field.
func ProgressMessageNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldProgressMessage, vs...))
}

// ProgressMessageGT applies the GT predicate on the "progress_message" field.
func ProgressMessageGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldProgressMessage, v))
}

// ProgressMessageGTE applies the GTE predicate on the "progress_message" field.
func ProgressMessageGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldProgressMessage, v))
}

// ProgressMessageLT applies the LT predicate on the "progress_message" field.
func ProgressMessageLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldProgressMessage, v))
}

// ProgressMessageLTE applies the LTE predicate on the "progress_message" field.
func ProgressMessageLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldProgressMessage, v))
}

// ProgressMessageContains applies the Contains predicate on the "progress_message" field.
func ProgressMessageContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldProgressMessage, v))
}

// ProgressMessageHasPrefix applies the HasPrefix predicate on the "progress_message" field.
func ProgressMessageHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldProgressMessage, v))
}

// ProgressMessageHasSuffix applies the HasSuffix predicate on the "progress_message" field.
func ProgressMessageHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldProgressMessage, v))
}

// ProgressMessageIsNil applies the IsNil predicate on the "progress_message" field.
func ProgressMessageIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldProgressMessage))
}

// ProgressMessageNotNil applies the NotNil predicate on the "progress_message" field.
func ProgressMessageNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldProgressMessage))
}

// ProgressMessageEqualFold applies the EqualFold predicate on the "progress_message" field.
func ProgressMessageEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldProgressMessage, v))
}

// ProgressMessageContainsFold applies the ContainsFold predicate on the "progress_message" field.
func ProgressMessageContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldProgressMessage, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldResult))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldError, v))
}

// SubmittedPayloadIsNil applies the IsNil predicate on the "submitted_payload" field.
func SubmittedPayloadIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldSubmittedPayload))
}

// SubmittedPayloadNotNil applies the NotNil predicate on the "submitted_payload" field.
func SubmittedPayloadNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldSubmittedPayload))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldAttemptCount, v))
}

// MaxRetriesEQ applies the EQ predicate on the "max_retries" field.
func MaxRetriesEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMaxRetries, v))
}

// MaxRetriesNEQ applies the NEQ predicate on the "max_retries" field.
func MaxRetriesNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldMaxRetries, v))
}

// MaxRetriesIn applies the In predicate on the "max_retries" field.
func MaxRetriesIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldMaxRetries, vs...))
}

// MaxRetriesNotIn applies the NotIn predicate on the "max_retries" field.
func MaxRetriesNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldMaxRetries, vs...))
}

// MaxRetriesGT applies the GT predicate on the "max_retries" field.
func MaxRetriesGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldMaxRetries, v))
}

// MaxRetriesGTE applies the GTE predicate on the "max_retries" field.
func MaxRetriesGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldMaxRetries, v))
}

// MaxRetriesLT applies the LT predicate on the "max_retries" field.
func MaxRetriesLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldMaxRetries, v))
}

// MaxRetriesLTE applies the LTE predicate on the "max_retries" field.
func MaxRetriesLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldMaxRetries, v))
}

// MaxDurationEQ applies the EQ predicate on the "max_duration" field.
func MaxDurationEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMaxDuration, v))
}

// MaxDurationNEQ applies the NEQ predicate on the "max_duration" field.
func MaxDurationNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldMaxDuration, v))
}

// MaxDurationIn applies the In predicate on the "max_duration" field.
func MaxDurationIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldMaxDuration, vs...))
}

// MaxDurationNotIn applies the NotIn predicate on the "max_duration" field.
func MaxDurationNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldMaxDuration, vs...))
}

// MaxDurationGT applies the GT predicate on the "max_duration" field.
func MaxDurationGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldMaxDuration, v))
}

// MaxDurationGTE applies the GTE predicate on the "max_duration" field.
func MaxDurationGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldMaxDuration, v))
}

// MaxDurationLT applies the LT predicate on the "max_duration" field.
func MaxDurationLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldMaxDuration, v))
}

// MaxDurationLTE applies the LTE predicate on the "max_duration" field.
func MaxDurationLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldMaxDuration, v))
}

// MaxDurationIsNil applies the IsNil predicate on the "max_duration" field.
func MaxDurationIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldMaxDuration))
}

// MaxDurationNotNil applies the NotNil predicate on the "max_duration" field.
func MaxDurationNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldMaxDuration))
}

// TotalDeadlineEQ applies the EQ predicate on the "total_deadline" field.
func TotalDeadlineEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTotalDeadline, v))
}

// TotalDeadlineNEQ applies the NEQ predicate on the "total_deadline" field.
func TotalDeadlineNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTotalDeadline, v))
}

// TotalDeadlineIn applies the In predicate on the "total_deadline" field.
func TotalDeadlineIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTotalDeadline, vs...))
}

// TotalDeadlineNotIn applies the NotIn predicate on the "total_deadline" field.
func TotalDeadlineNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTotalDeadline, vs...))
}

// TotalDeadlineGT applies the GT predicate on the "total_deadline" field.
func TotalDeadlineGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldTotalDeadline, v))
}

// TotalDeadlineGTE applies the GTE predicate on the "total_deadline" field.
func TotalDeadlineGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldTotalDeadline, v))
}

// TotalDeadlineLT applies the LT predicate on the "total_deadline" field.
func TotalDeadlineLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldTotalDeadline, v))
}

// TotalDeadlineLTE applies the LTE predicate on the "total_deadline" field.
func TotalDeadlineLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldTotalDeadline, v))
}

// TotalDeadlineIsNil applies the IsNil predicate on the "total_deadline" field.
func TotalDeadlineIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldTotalDeadline))
}

// TotalDeadlineNotNil applies the NotNil predicate on the "total_deadline" field.
func TotalDeadlineNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldTotalDeadline))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIsNil applies the IsNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldLeaseExpiresAt))
}

// LeaseExpiresAtNotNil applies the NotNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldLeaseExpiresAt))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIsNil applies the IsNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldLastHeartbeatAt))
}

// LastHeartbeatAtNotNil applies the NotNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldLastHeartbeatAt))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedByEQ applies the EQ predicate on the "submitted_by" field.
func SubmittedByEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSubmittedBy, v))
}

// SubmittedByNEQ applies the NEQ predicate on the "submitted_by" field.
func SubmittedByNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSubmittedBy, v))
}

// SubmittedByIn applies the In predicate on the "submitted_by" field.
func SubmittedByIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSubmittedBy, vs...))
}

// SubmittedByNotIn applies the NotIn predicate on the "submitted_by" field.
func SubmittedByNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSubmittedBy, vs...))
}

// SubmittedByGT applies the GT predicate on the "submitted_by" field.
func SubmittedByGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSubmittedBy, v))
}

// SubmittedByGTE applies the GTE predicate on the "submitted_by" field.
func SubmittedByGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSubmittedBy, v))
}

// SubmittedByLT applies the LT predicate on the "submitted_by" field.
func SubmittedByLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSubmittedBy, v))
}

// SubmittedByLTE applies the LTE predicate on the "submitted_by" field.
func SubmittedByLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSubmittedBy, v))
}

// SubmittedByContains applies the Contains predicate on the "submitted_by" field.
func SubmittedByContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldSubmittedBy, v))
}

// SubmittedByHasPrefix applies the HasPrefix predicate on the "submitted_by" field.
func SubmittedByHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldSubmittedBy, v))
}

// SubmittedByHasSuffix applies the HasSuffix predicate on the "submitted_by" field.
func SubmittedByHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldSubmittedBy, v))
}

// SubmittedByIsNil applies the IsNil predicate on the "submitted_by" field.
func SubmittedByIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldSubmittedBy))
}

// SubmittedByNotNil applies the NotNil predicate on the "submitted_by" field.
func SubmittedByNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldSubmittedBy))
}

// SubmittedByEqualFold applies the EqualFold predicate on the "submitted_by" field.
func SubmittedByEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldSubmittedBy, v))
}

// SubmittedByContainsFold applies the ContainsFold predicate on the "submitted_by" field.
func SubmittedByContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldSubmittedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
