apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: "loki"
        tags: ["job", "instance", "pod", "namespace"]
        mappedTags:
          - key: "service.name"
            value: "service"
        mapTagNamesEnabled: false
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: false
        filterBySpanID: false
      lokiSearch:
        datasourceUid: "loki"
      serviceMap:
        datasourceUid: "prometheus"
