# Docker Compose Override for Development
# This file provides development-friendly overrides that work better for local builds
# Usage: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

version: "3.8"

services:
  # Override base image build for local development
  mcp-mesh-base:
    build:
      platforms: [] # Remove multi-platform for faster local builds

  # Override registry build for local development
  registry:
    build:
      platforms: [] # Remove multi-platform for faster local builds
    # Add development-friendly environment variables
    environment:
      - MCP_MESH_LOG_LEVEL=DEBUG
      - MCP_MESH_DEBUG_MODE=true

  # Override hello-world-agent for development
  hello-world-agent:
    environment:
      - MCP_MESH_LOG_LEVEL=DEBUG
      - MCP_MESH_DEBUG_MODE=true
    # Mount source code for live development (optional)
    # volumes:
    #   - ./agents/hello-world:/app

  # Override system-agent for development
  system-agent:
    environment:
      - MCP_MESH_LOG_LEVEL=DEBUG
      - MCP_MESH_DEBUG_MODE=true
    # Mount source code for live development (optional)
    # volumes:
    #   - ./agents/system-agent:/app
