version: "3.8"

# MCP Mesh Docker Compose Example
# Demonstrates Go registry + Python agents using published Docker images
#
# Services:
# - registry: Go-based registry (mcpmesh/registry:0.1.1)
# - hello-world-agent: Python agent with greeting capabilities (mcpmesh/python-runtime:0.1.1)
# - system-agent: Python agent with system monitoring capabilities (mcpmesh/python-runtime:0.1.1)
#
# Usage:
#   docker-compose up
#
# Access points:
#   - Registry API: http://localhost:8000
#   - Hello World Agent: http://localhost:8081
#   - System Agent: http://localhost:8082
#   - Use meshctl to interact with the mesh

services:
  # Go-based registry service - uses published Docker image
  registry:
    image: mcpmesh/registry:0.1.1
    container_name: mcp-mesh-registry
    ports:
      - "8000:8000"
    environment:
      # Registry configuration - use the actual env vars the Go registry expects
      - HOST=${REGISTRY_HOST:-0.0.0.0}
      - PORT=${REGISTRY_PORT:-8000}
      - MCP_MESH_LOG_LEVEL=${MCP_MESH_LOG_LEVEL:-INFO}
      - MCP_MESH_DEBUG_MODE=${MCP_MESH_DEBUG_MODE:-false}
    volumes:
      - registry_data:/data
    networks:
      - mcp-mesh
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Hello World Python agent - uses published Docker image
  hello-world-agent:
    image: mcpmesh/python-runtime:0.1.1
    container_name: mcp-mesh-hello-world
    hostname: hello-world-agent
    ports:
      - "${HELLO_WORLD_PORT:-8081}:${MCP_MESH_HTTP_PORT:-8080}"
    volumes:
      # Mount agent code from outside
      - ../simple/hello_world.py:/app/agent.py:ro
    working_dir: /app
    command: ["python", "agent.py"]
    environment:
      # MCP Mesh configuration - agent works standalone if registry unavailable
      - MCP_MESH_REGISTRY_URL=http://registry:8000
      - MCP_MESH_REGISTRY_HOST=registry
      - MCP_MESH_REGISTRY_PORT=8000
      - HOST=0.0.0.0
      - MCP_MESH_HTTP_HOST=hello-world-agent
      - MCP_MESH_HTTP_PORT=${MCP_MESH_HTTP_PORT:-8080}
      - POD_IP=hello-world-agent
      - MCP_MESH_HTTP_ENABLED=true
      - MCP_MESH_AGENT_NAME=hello-world
      - MCP_MESH_NAMESPACE=${MCP_MESH_NAMESPACE:-default}
      - MCP_MESH_ENABLED=true
      - MCP_MESH_AUTO_RUN=${MCP_MESH_AUTO_RUN:-true}
      - MCP_MESH_AUTO_RUN_INTERVAL=${MCP_MESH_AUTO_RUN_INTERVAL:-30}
      - MCP_MESH_HEALTH_INTERVAL=${MCP_MESH_HEALTH_INTERVAL:-30}
      - MCP_MESH_LOG_LEVEL=${MCP_MESH_LOG_LEVEL:-INFO}
      - MCP_MESH_DEBUG_MODE=${MCP_MESH_DEBUG_MODE:-false}
      - MCP_MESH_DYNAMIC_UPDATES=${MCP_MESH_DYNAMIC_UPDATES:-true}
      - MCP_MESH_UPDATE_STRATEGY=${MCP_MESH_UPDATE_STRATEGY:-immediate}
    depends_on:
      # Wait for registry to be ready
      registry:
        condition: service_healthy
    networks:
      - mcp-mesh
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:${MCP_MESH_HTTP_PORT:-8080}/health', timeout=5)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  # System Agent Python service - uses published Docker image
  system-agent:
    image: mcpmesh/python-runtime:0.1.1
    container_name: mcp-mesh-system-agent
    hostname: system-agent
    ports:
      - "${SYSTEM_AGENT_PORT:-8082}:${MCP_MESH_HTTP_PORT:-8080}"
    volumes:
      # Mount agent code from outside
      - ../simple/system_agent.py:/app/agent.py:ro
    working_dir: /app
    command: ["python", "agent.py"]
    environment:
      # MCP Mesh configuration - agent works standalone if registry unavailable
      - MCP_MESH_REGISTRY_URL=http://registry:8000
      - MCP_MESH_REGISTRY_HOST=registry
      - MCP_MESH_REGISTRY_PORT=8000
      - HOST=0.0.0.0
      - MCP_MESH_HTTP_HOST=system-agent
      - MCP_MESH_HTTP_PORT=${MCP_MESH_HTTP_PORT:-8080}
      - POD_IP=system-agent
      - MCP_MESH_HTTP_ENABLED=true
      - MCP_MESH_AGENT_NAME=system-agent
      - MCP_MESH_NAMESPACE=${MCP_MESH_NAMESPACE:-default}
      - MCP_MESH_ENABLED=true
      - MCP_MESH_AUTO_RUN=${MCP_MESH_AUTO_RUN:-true}
      - MCP_MESH_AUTO_RUN_INTERVAL=${MCP_MESH_AUTO_RUN_INTERVAL:-30}
      - MCP_MESH_HEALTH_INTERVAL=${MCP_MESH_HEALTH_INTERVAL:-30}
      - MCP_MESH_LOG_LEVEL=${MCP_MESH_LOG_LEVEL:-INFO}
      - MCP_MESH_DEBUG_MODE=${MCP_MESH_DEBUG_MODE:-false}
      - MCP_MESH_DYNAMIC_UPDATES=${MCP_MESH_DYNAMIC_UPDATES:-true}
      - MCP_MESH_UPDATE_STRATEGY=${MCP_MESH_UPDATE_STRATEGY:-immediate}
    depends_on:
      # Wait for registry to be ready
      registry:
        condition: service_healthy
    networks:
      - mcp-mesh
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:${MCP_MESH_HTTP_PORT:-8080}/health', timeout=5)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  mcp-mesh:
    driver: bridge
    name: mcp-mesh-network

volumes:
  registry_data:
    name: mcp-mesh-registry-data
