{{- if .Values.agentCode.enabled }}
{{- if .Values.agentCode.scriptPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-mesh-agent.fullname" . }}-code
  labels:
    {{- include "mcp-mesh-agent.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  agent.py: |
{{ .Files.Get .Values.agentCode.scriptPath | indent 4 }}
{{- end }}
{{- end }}
