/* MCP Mesh Core - C FFI Bindings
 *
 * Auto-generated by cbindgen. Do not modify manually.
 *
 * This header provides C-compatible bindings for the MCP Mesh Rust core,
 * enabling integration with TypeScript, Kotlin, and other languages.
 *
 * Usage:
 *   1. Link with libmcp_mesh_core.so (Linux), libmcp_mesh_core.dylib (macOS),
 *      or mcp_mesh_core.dll (Windows)
 *   2. Include this header
 *   3. Call mesh_start_agent() with JSON spec to start an agent
 *   4. Use mesh_next_event() to receive topology events
 *   5. Call mesh_shutdown() and mesh_free_handle() on cleanup
 *
 * Functions:
 *   - mesh_start_agent(spec_json) - Start an agent, returns handle
 *   - mesh_next_event(handle, timeout_ms) - Poll for next event (JSON string)
 *   - mesh_is_running(handle) - Check if agent is running (returns 1/0)
 *   - mesh_report_health(handle, status_json) - Report health status (returns 0 on success, -1 on error)
 *   - mesh_shutdown(handle) - Signal agent to shut down
 *   - mesh_last_error() - Get last error message for current thread
 *   - mesh_version() - Get library version string
 *
 * Memory Management:
 *   - Strings returned by mesh_* functions must be freed with mesh_free_string()
 *   - Handles returned by mesh_start_agent() must be freed with mesh_free_handle()
 *   - mesh_version() returns a static string that must NOT be freed
 *
 * Thread Safety:
 *   - All functions are thread-safe
 *   - mesh_last_error() is thread-local
 */


#ifndef MCP_MESH_CORE_H
#define MCP_MESH_CORE_H

/* Generated with cbindgen:0.27.0 */

/* Warning: This file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle wrapping a [`JobController`] plus its background batching
// tick. The tick is held alongside the controller so it lives until the
// caller invokes [`mesh_job_controller_free`] (mirrors PyJobController /
// JsJobController which both keep a `BatchingHandle` field).
//
// Not `#[repr(C)]` — internals stay opaque to C consumers.
typedef struct JobControllerHandle JobControllerHandle;

// Opaque handle wrapping a [`JobProxy`].
typedef struct JobProxyHandle JobProxyHandle;

// Opaque handle to a running MCP Mesh agent.
//
// This struct holds all resources needed to interact with the agent runtime.
// It must be freed with `mesh_free_handle` when no longer needed.
//
// Note: This struct is intentionally NOT `#[repr(C)]` to keep its internals
// opaque to C consumers. The FFI functions work with raw pointers.
typedef struct MeshAgentHandle MeshAgentHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Start an agent from JSON specification.
//
// # Arguments
// * `spec_json` - JSON string containing AgentSpec
//
// # Returns
// Handle to agent, or NULL on error (check `mesh_last_error`)
//
// # Safety
// * `spec_json` must be a valid null-terminated C string
// * The returned handle must be freed with `mesh_free_handle`
struct MeshAgentHandle *mesh_start_agent(const char *spec_json);

// Request graceful shutdown of agent.
//
// Sends unregister to registry, stops heartbeat loop.
// Non-blocking - use `mesh_next_event` to wait for shutdown event.
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent`
void mesh_shutdown(struct MeshAgentHandle *handle);

// Free agent handle and associated resources.
//
// If the agent is still running, this will trigger graceful shutdown
// and wait briefly (up to 2 seconds) for the agent to unregister from
// the registry before dropping resources.
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent` or NULL
// * After this call, `handle` is invalid and must not be used
void mesh_free_handle(struct MeshAgentHandle *handle);

// Get next event from agent runtime.
//
// Blocks until event available or timeout.
//
// # Arguments
// * `handle` - Agent handle
// * `timeout_ms` - Timeout in milliseconds (-1 for infinite, 0 for non-blocking)
//
// # Returns
// JSON string (caller must free with `mesh_free_string`), or NULL on timeout/shutdown
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent`
// * The returned string must be freed with `mesh_free_string`
char *mesh_next_event(struct MeshAgentHandle *handle, int64_t timeout_ms);

// Check if agent is still running.
//
// # Arguments
// * `handle` - Agent handle
//
// # Returns
// 1 if running, 0 if shutdown/error
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent`
int32_t mesh_is_running(const struct MeshAgentHandle *handle);

// Report agent health status.
//
// # Arguments
// * `handle` - Agent handle
// * `status` - Health status: "healthy", "degraded", or "unhealthy"
//
// # Returns
// 0 on success, -1 on error
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent`
// * `status` must be a valid null-terminated C string
int32_t mesh_report_health(struct MeshAgentHandle *handle, const char *status);

// Update the HTTP port after auto-detection.
//
// Call this after the HTTP server starts with port=0 to update
// the registry with the actual assigned port. Triggers a full
// heartbeat to re-register with the correct endpoint.
//
// # Arguments
// * `handle` - Agent handle
// * `port` - The actual port the HTTP server is listening on
//
// # Returns
// 0 on success, -1 on error
//
// # Safety
// * `handle` must be a valid handle from `mesh_start_agent`
int32_t mesh_update_port(struct MeshAgentHandle *handle, int32_t port);

// Get last error message.
//
// Thread-local, cleared on next `mesh_*` call.
//
// # Returns
// Error message (caller must free with `mesh_free_string`), or NULL if no error
//
// # Safety
// * The returned string must be freed with `mesh_free_string`
char *mesh_last_error(void);

// Free string returned by `mesh_*` functions.
//
// # Safety
// * `s` must be a string returned by a `mesh_*` function or NULL
// * After this call, `s` is invalid and must not be used
void mesh_free_string(char *s);

// Resolve configuration value with priority: ENV > param > default.
//
// For http_host, auto-detects external IP if no value provided.
//
// # Arguments
// * `key_name` - Config key (e.g., "http_host", "registry_url", "namespace")
// * `param_value` - Optional value from code/config (NULL for none)
//
// # Returns
// Resolved value (caller must free with `mesh_free_string`), or NULL if unknown key
//
// # Safety
// * `key_name` must be a valid null-terminated C string
// * `param_value` may be NULL or a valid null-terminated C string
// * The returned string must be freed with `mesh_free_string`
char *mesh_resolve_config(const char *key_name, const char *param_value);

// Resolve integer configuration value with priority: ENV > param > default.
//
// # Arguments
// * `key_name` - Config key (e.g., "http_port", "health_interval")
// * `param_value` - Value from code/config (-1 for none)
//
// # Returns
// Resolved value, or -1 if unknown key or no value available
//
// # Safety
// * `key_name` must be a valid null-terminated C string
int64_t mesh_resolve_config_int(const char *key_name, int64_t param_value);

// Auto-detect external IP address.
//
// Uses UDP socket trick to find IP that routes to external networks.
// Falls back to "localhost" if detection fails.
//
// # Returns
// IP address string (caller must free with `mesh_free_string`)
//
// # Safety
// * The returned string must be freed with `mesh_free_string`
char *mesh_auto_detect_ip(void);

// Get library version string.
//
// # Returns
// Version string (do not free)
const char *mesh_version(void);

// Get TLS configuration resolved from environment variables.
//
// Returns a JSON string with the TLS config:
// ```json
// {
//   "enabled": true,
//   "mode": "auto",
//   "cert_path": "/path/to/cert.pem",
//   "key_path": "/path/to/key.pem",
//   "ca_path": "/path/to/ca.pem"
// }
// ```
//
// When TLS is off, returns:
// ```json
// {"enabled": false, "mode": "off", "cert_path": null, "key_path": null, "ca_path": null}
// ```
//
// # Returns
// * JSON string (caller must free with `mesh_free_string`)
// * NULL on error (check `mesh_last_error`)
char *mesh_get_tls_config(void);

// Prepare TLS credentials (fetch from provider, write secure temp files).
//
// Must be called early in agent startup, before HTTP server starts.
// Results are cached globally -- subsequent calls to `mesh_get_tls_config()`
// will return the resolved config with temp file paths.
//
// # Arguments
// * `agent_name` - Agent name for certificate CN (e.g., "greeter-abc123")
//
// # Returns
// * JSON string with TLS config (caller must free with `mesh_free_string`)
// * NULL on error (check `mesh_last_error`)
//
// # Safety
// * `agent_name` must be a valid null-terminated C string
char *mesh_prepare_tls(const char *agent_name);

// Clean up temporary TLS credential files.
//
// Call during agent shutdown. Safe to call multiple times.
void mesh_cleanup_tls(void);

// Check if distributed tracing is enabled.
//
// Checks MCP_MESH_DISTRIBUTED_TRACING_ENABLED environment variable.
//
// # Returns
// 1 if tracing is enabled, 0 otherwise
int32_t mesh_is_tracing_enabled(void);

// Initialize the trace publisher.
//
// Must be called before `mesh_publish_span`. Connects to Redis.
//
// # Returns
// 1 on success (Redis connected), 0 on failure
int32_t mesh_init_trace_publisher(void);

// Check if trace publisher is available.
//
// # Returns
// 1 if publisher is initialized and ready, 0 otherwise
int32_t mesh_is_trace_publisher_available(void);

// Publish a trace span to Redis.
//
// Non-blocking (from the caller's perspective) - returns after queuing the span.
// Silently handles failures to never break agent operations.
//
// # Arguments
// * `span_json` - JSON string containing span data (all values should be strings)
//
// # Returns
// 1 on success (queued), 0 on failure
//
// # Safety
// * `span_json` must be a valid null-terminated C string
int32_t mesh_publish_span(const char *span_json);

// Extract JSON from LLM response text.
//
// Strategies (in order):
// 1. Find ```json...``` code blocks
// 2. Progressive JSON object extraction
// 3. Progressive JSON array extraction
//
// # Arguments
// * `text` - Raw LLM response text
//
// # Returns
// Extracted JSON string (caller must free with `mesh_free_string`), or NULL if no JSON found
//
// # Safety
// * `text` must be a valid null-terminated C string
char *mesh_extract_json(const char *text);

// Strip markdown code fences from content.
//
// # Arguments
// * `text` - Text with potential code fences
//
// # Returns
// Text with fences removed (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `text` must be a valid null-terminated C string
char *mesh_strip_code_fences(const char *text);

// Make a JSON schema strict for structured output.
//
// Adds additionalProperties: false to all object types and optionally
// sets required to include all property keys.
//
// # Arguments
// * `schema_json` - JSON schema string
// * `add_all_required` - 1 to add all properties to required, 0 to skip
//
// # Returns
// Modified schema JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `schema_json` must be a valid null-terminated C string
char *mesh_make_schema_strict(const char *schema_json, int32_t add_all_required);

// Sanitize a JSON schema by removing unsupported validation keywords.
//
// # Arguments
// * `schema_json` - JSON schema string
//
// # Returns
// Sanitized schema JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `schema_json` must be a valid null-terminated C string
char *mesh_sanitize_schema(const char *schema_json);

// Check if any tool schema property contains x-media-type.
//
// # Arguments
// * `schema_json` - JSON schema string (OpenAI tool format or bare schema)
//
// # Returns
// 1 if media params found, 0 otherwise
//
// # Safety
// * `schema_json` must be a valid null-terminated C string
int32_t mesh_detect_media_params(const char *schema_json);

// Check if a JSON schema is simple enough for hint mode.
//
// # Arguments
// * `schema_json` - JSON schema string
//
// # Returns
// 1 if simple, 0 otherwise
//
// # Safety
// * `schema_json` must be a valid null-terminated C string
int32_t mesh_is_simple_schema(const char *schema_json);

// Normalize a raw JSON Schema and return a JSON envelope with
// `{canonical, hash, verdict, warnings}`.
//
// This is the C FFI wrapper around `schema_normalize::normalize_schema`
// (issue #547). Mirrors the Python (`normalize_schema_py`) and napi
// (`normalize_schema`) bindings so Java SDKs can produce identical
// canonical forms and hashes for cross-runtime capability matching.
//
// # Arguments
// * `raw_json` - Raw JSON Schema string
// * `origin` - Origin runtime hint: "python", "typescript", "java", or unknown.
//   May be NULL.
//
// # Returns
// JSON string with fields `canonical`, `hash`, `verdict`, `warnings`
// (caller must free with `mesh_free_string`). On error returns a JSON
// envelope with `verdict="BLOCK"` rather than NULL so callers can always
// parse the response.
//
// # Safety
// * `raw_json` must be a valid null-terminated C string
// * `origin` may be NULL or a valid null-terminated C string
// * The returned string must be freed with `mesh_free_string`
char *mesh_normalize_schema(const char *raw_json, const char *origin);

// Generate OpenTelemetry-compliant trace ID (32-char hex, 128-bit).
//
// # Returns
// Trace ID string (caller must free with `mesh_free_string`), or NULL on error
char *mesh_generate_trace_id(void);

// Generate OpenTelemetry-compliant span ID (16-char hex, 64-bit).
//
// # Returns
// Span ID string (caller must free with `mesh_free_string`), or NULL on error
char *mesh_generate_span_id(void);

// Inject trace context into JSON-RPC arguments.
//
// # Arguments
// * `args_json` - JSON object string with existing arguments
// * `trace_id` - Trace ID to inject
// * `span_id` - Span ID to inject as _parent_span
// * `propagated_headers_json` - Optional JSON object of headers to propagate (may be NULL)
//
// # Returns
// Modified JSON string (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `args_json`, `trace_id`, and `span_id` must be valid null-terminated C strings
// * `propagated_headers_json` may be NULL
char *mesh_inject_trace_context(const char *args_json,
                                const char *trace_id,
                                const char *span_id,
                                const char *propagated_headers_json);

// Extract trace context from HTTP headers with body fallback.
//
// # Arguments
// * `headers_json` - JSON object of HTTP headers
// * `body_json` - Optional JSON-RPC body (may be NULL)
//
// # Returns
// JSON string with trace_id and parent_span (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `headers_json` must be a valid null-terminated C string
// * `body_json` may be NULL
char *mesh_extract_trace_context(const char *headers_json,
                                 const char *body_json);

// Filter headers by propagation allowlist with prefix matching.
//
// # Arguments
// * `headers_json` - JSON object of HTTP headers
// * `allowlist_csv` - Comma-separated list of header prefixes
//
// # Returns
// JSON string of matching headers (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * Both parameters must be valid null-terminated C strings
char *mesh_filter_propagation_headers(const char *headers_json, const char *allowlist_csv);

// Check if a header matches the propagation allowlist.
//
// # Arguments
// * `header_name` - Header name to check
// * `allowlist_csv` - Comma-separated list of header prefixes
//
// # Returns
// 1 if matches, 0 otherwise
//
// # Safety
// * Both parameters must be valid null-terminated C strings
int32_t mesh_matches_propagate_header(const char *header_name, const char *allowlist_csv);

// Build a JSON-RPC 2.0 request envelope.
//
// # Arguments
// * `method` - JSON-RPC method name
// * `params_json` - JSON string for params
// * `request_id` - Unique request identifier
//
// # Returns
// JSON-RPC request string (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * All parameters must be valid null-terminated C strings
char *mesh_build_jsonrpc_request(const char *method,
                                 const char *params_json,
                                 const char *request_id);

// Generate a unique request ID.
//
// # Returns
// Request ID string (caller must free with `mesh_free_string`)
char *mesh_generate_request_id(void);

// Parse SSE or plain JSON response.
//
// # Arguments
// * `response_text` - Raw response body
//
// # Returns
// Extracted JSON string (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `response_text` must be a valid null-terminated C string
char *mesh_parse_sse_response(const char *response_text);

// Extract text content from MCP CallToolResult.
//
// # Arguments
// * `result_json` - JSON string of the MCP result
//
// # Returns
// Extracted content string (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `result_json` must be a valid null-terminated C string
char *mesh_extract_content(const char *result_json);

// Call a remote MCP tool via HTTP POST with retry.
//
// # Arguments
// * `endpoint` - MCP endpoint URL
// * `tool_name` - Name of the tool to call
// * `args_json` - Optional JSON string of tool arguments (may be NULL)
// * `headers_json` - Optional JSON object of extra headers (may be NULL)
// * `timeout_ms` - Request timeout in milliseconds
// * `max_retries` - Maximum number of retries on network error
//
// # Returns
// Result string (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `endpoint` and `tool_name` must be valid null-terminated C strings
// * `args_json` and `headers_json` may be NULL
char *mesh_call_tool(const char *endpoint,
                     const char *tool_name,
                     const char *args_json,
                     const char *headers_json,
                     int64_t timeout_ms,
                     int32_t max_retries);

// Determine output mode for a vendor given the context.
//
// # Arguments
// * `provider` - Vendor name (e.g., "anthropic", "openai", "gemini")
// * `is_string_type` - 1 if the output schema is a plain string type
// * `has_tools` - 1 if tools are present in the request
// * `override_mode` - Optional override mode (may be NULL)
//
// # Returns
// Output mode string: "text", "hint", or "strict" (caller must free with `mesh_free_string`)
//
// # Safety
// * `provider` must be a valid null-terminated C string
// * `override_mode` may be NULL
char *mesh_determine_output_mode(const char *provider,
                                 int32_t is_string_type,
                                 int32_t has_tools,
                                 const char *override_mode);

// Build the complete system prompt with vendor-specific additions.
//
// # Arguments
// * `provider` - Vendor name
// * `base_prompt` - Base system prompt text
// * `has_tools` - 1 if tools are present
// * `has_media_params` - 1 if media parameters are present
// * `schema_json` - Optional JSON schema string (may be NULL)
// * `schema_name` - Optional schema name (may be NULL)
// * `output_mode` - Output mode: "text", "hint", or "strict"
//
// # Returns
// Complete system prompt (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `provider`, `base_prompt`, and `output_mode` must be valid null-terminated C strings
// * `schema_json` and `schema_name` may be NULL
char *mesh_format_system_prompt(const char *provider,
                                const char *base_prompt,
                                int32_t has_tools,
                                int32_t has_media_params,
                                const char *schema_json,
                                const char *schema_name,
                                const char *output_mode);

// Build the `response_format` JSON object for vendors that support it.
//
// # Arguments
// * `provider` - Vendor name
// * `schema_json` - JSON schema string
// * `schema_name` - Schema name for the response_format
// * `has_tools` - 1 if tools are present
//
// # Returns
// JSON string with response_format (caller must free with `mesh_free_string`),
// or NULL if vendor does not support response_format for this scenario
//
// # Safety
// * All parameters must be valid null-terminated C strings
char *mesh_build_response_format(const char *provider,
                                 const char *schema_json,
                                 const char *schema_name,
                                 int32_t has_tools);

// Get vendor capabilities as JSON.
//
// # Arguments
// * `provider` - Vendor name
//
// # Returns
// JSON string with vendor capabilities (caller must free with `mesh_free_string`),
// or NULL on error
//
// # Safety
// * `provider` must be a valid null-terminated C string
char *mesh_get_vendor_capabilities(const char *provider);

// Create initial agentic loop state.
//
// # Arguments
// * `config_json` - JSON config with `messages` array and optional `max_iterations`
//
// # Returns
// Action JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `config_json` must be a valid null-terminated C string
char *mesh_create_agentic_loop(const char *config_json);

// Process an LLM response in the agentic loop.
//
// # Arguments
// * `state_json` - Serialized loop state from a previous call
// * `llm_response_json` - LLM response with optional `tool_calls`, `content`, `usage`
//
// # Returns
// Action JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * Both parameters must be valid null-terminated C strings
char *mesh_process_llm_response(const char *state_json, const char *llm_response_json);

// Add tool execution results to the agentic loop.
//
// # Arguments
// * `state_json` - Serialized loop state from a previous call
// * `tool_results_json` - Array of `{"tool_call_id": "...", "content": "..."}`
//
// # Returns
// Action JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * Both parameters must be valid null-terminated C strings
char *mesh_add_tool_results(const char *state_json, const char *tool_results_json);

// Get a read-only view of the agentic loop state.
//
// # Arguments
// * `state_json` - Serialized loop state
//
// # Returns
// State info JSON (caller must free with `mesh_free_string`), or NULL on error
//
// # Safety
// * `state_json` must be a valid null-terminated C string
char *mesh_get_loop_state(const char *state_json);

// Construct a [`JobController`] bound to `(job_id, instance_id)` against the
// given `registry_url`. Spawns a per-controller background batching tick so
// mid-flight `update_progress` calls reach the registry on the configured
// cadence (default 2s — see [`BatchingConfig::default`]); the tick is torn
// down with a final flush when the handle is freed.
//
// # Returns
// 0 on success (handle written to `*out_handle`), non-zero on error
// (check `mesh_last_error`).
//
// # Safety
// All input strings must be valid null-terminated UTF-8. `out_handle`
// must point to writable memory for one `*mut JobControllerHandle`.
int32_t mesh_job_controller_new(const char *job_id,
                                const char *instance_id,
                                const char *registry_url,
                                struct JobControllerHandle **out_handle);

// Enqueue a progress update. Coalesces with any prior pending progress
// for this job — only the latest survives the next batch flush.
//
// `message` may be NULL (no message).
//
// # Safety
// `handle` must come from [`mesh_job_controller_new`] and must not yet
// have been freed.
int32_t mesh_job_controller_update_progress(struct JobControllerHandle *handle,
                                            double progress,
                                            const char *message);

// Mark the job complete with the given result (JSON-encoded). Flushes
// immediately.
//
// # Safety
// `result_json` must be a valid JSON string (UTF-8). Invalid JSON
// returns -1 with last-error set.
int32_t mesh_job_controller_complete(struct JobControllerHandle *handle, const char *result_json);

// Mark the job failed with the given error reason. Flushes immediately.
int32_t mesh_job_controller_fail(struct JobControllerHandle *handle, const char *error);

// Voluntarily release the lease so a peer replica can re-claim and
// retry. Used by the Java SDK dispatch wrapper when a handler raises
// a retryOn-matched exception (#895). `reason` may be NULL for
// "no reason given"; an empty string is passed through as `Some("")`
// for parity with `mesh_job_proxy_cancel`.
//
// See [`crate::jobs::JobController::release_lease`] for full semantics.
// Note: release does NOT increment `attempt_count` — the claim that
// picked the row up already counted this attempt; the next claim will
// count the next attempt.
//
// Marks the controller terminal locally before the backend call so
// racing `update_progress` from this defunct attempt is fenced (mirror
// of Python's / TS's release_lease contract).
int32_t mesh_job_controller_release_lease(struct JobControllerHandle *handle, const char *reason);

// Whether `complete` / `fail` has already been called on this controller.
//
// # Returns
// `1` if terminal, `0` if not, `-1` on error.
int32_t mesh_job_controller_is_terminal(const struct JobControllerHandle *handle);

// Whether the cancel token bound to this controller's job in the
// process-wide cancel registry has been fired. Returns `0` (not cancelled)
// when the job is not currently registered (no [`mesh_run_as_job`] scope
// active). Used by per-language SDKs whose blocking primitives cannot be
// interrupted by a Tokio cancel token firing — e.g. the Java fixture's
// `runs_overlong` polls this between `Thread.sleep` intervals so a
// mid-flight cancel can break out of the loop instead of running to
// natural completion. Distinct from [`mesh_job_controller_is_terminal`]:
// terminal reflects local complete/fail/release intent; cancelled
// reflects an external cancel signal (HTTP route, deadline trip, etc.).
//
// # Returns
// `1` if cancel token fired, `0` if not (or job not registered),
// `-1` on error.
int32_t mesh_job_controller_is_cancelled(const struct JobControllerHandle *handle);

// Wait for the next event posted to this job's event channel.
//
// Mirrors [`JobController::recv_event`]. Returns the event as a JSON
// string written to `*out_event_json`, or a null pointer when the
// timeout elapses without a matching event. Cursor is per-controller-
// instance (shared across `clone`s); a fresh controller for the same
// `job_id` replays from seq=0.
//
// # Arguments
// - `types_json`: optional UTF-8 NUL-terminated JSON string encoding an
//   array of event-type tags. `NULL` (or a JSON `null`) means "receive
//   all types". Invalid JSON or non-array shape returns -1 with the
//   last-error slot populated.
// - `timeout_secs`: f64 timeout in seconds. The C ABI cannot pass
//   `Option<f64>`, so the convention is: pass a negative value (e.g.
//   `-1.0`) to express "no timeout" (mirrors `Optional<Duration>::empty()`
//   on the Java side). NaN / ±Infinity reject with -1. Finite-but-
//   overflowing values (e.g. `f64::MAX`) reject with -1 via
//   [`Duration::try_from_secs_f64`] — see `parse_ffi_timeout_secs`.
// - `out_event_json`: receives `*mut c_char` JSON string of the event
//   on arrival, or a NULL pointer on clean timeout (in which case the
//   return code is still 0). Caller frees via `mesh_free_string` when
//   the pointer is non-null.
//
// # Returns
// - `0` on success (event delivered OR clean timeout — caller checks
//   if `*out_event_json` is null to distinguish)
// - `-1` on invalid args (null handle, malformed types_json, invalid
//   timeout)
// - `-2` on JobNotFound (registry doesn't know the job — typically
//   "404 Not Found" from `GET /jobs/{id}/events`). Distinct from the
//   generic -3 so the Java SDK can map to a typed
//   `JobNotFoundException`.
// - `-3` on other backend errors (5xx after retries, network failure,
//   etc.). See `mesh_last_error` for details.
int32_t mesh_job_controller_recv_event(struct JobControllerHandle *handle,
                                       const char *types_json,
                                       double timeout_secs,
                                       char **out_event_json);

// Read the job ID this controller is bound to. Caller frees the returned
// string via `mesh_free_string`.
int32_t mesh_job_controller_job_id(const struct JobControllerHandle *handle, char **out_job_id);

// Free a [`JobControllerHandle`] returned by [`mesh_job_controller_new`].
//
// Drops the inner controller AND the background batching tick (which
// triggers a final flush of any pending deltas before the tick stops).
//
// # Safety
// `handle` must come from [`mesh_job_controller_new`] or be NULL. After
// this call, `handle` is invalid and must not be used.
void mesh_job_controller_free(struct JobControllerHandle *handle);

// Submit a new job via the registry and return a [`JobProxyHandle`].
//
// `args_json` must encode a JSON object with these fields (mirroring
// [`SubmitJobArgs`] field-for-field):
//
// ```json
// {
//   "registry_url": "http://...",
//   "capability": "...",
//   "payload": { ... },
//   "submitted_by": "...",
//   "owner_instance_id": "..." | null,
//   "max_duration": 120 | null,
//   "max_retries": 1 | null,
//   "total_deadline": 1700000000 | null
// }
// ```
//
// JSON-shaped (rather than positional) args mirror the napi-rs
// `JsSubmitJobArgs` object — keeps the C ABI signature stable as fields
// are added.
int32_t mesh_submit_job(const char *args_json, struct JobProxyHandle **out_handle);

// Construct a [`JobProxyHandle`] bound to a known job id + registry URL.
// Normally callers obtain a proxy via [`mesh_submit_job`] / DDDI injection
// rather than constructing one directly.
int32_t mesh_job_proxy_new(const char *job_id,
                           const char *registry_url,
                           struct JobProxyHandle **out_handle);

// Read the job id this proxy is bound to. Caller frees via `mesh_free_string`.
int32_t mesh_job_proxy_job_id(const struct JobProxyHandle *handle, char **out_job_id);

// Read the latest job state from the registry (single GET). The full Job
// row is serialized as JSON and written to `*out_job_json`; caller frees
// via `mesh_free_string`.
int32_t mesh_job_proxy_status(struct JobProxyHandle *handle, char **out_job_json);

// Poll until the job reaches a terminal state. On success writes the job
// `result` (JSON-encoded) to `*out_result_json`; caller frees via
// `mesh_free_string`.
//
// `timeout_secs`: wall-clock timeout. Any value `<= 0.0` (including
// `-0.0` and negatives such as `-1`) means "no timeout"; non-finite
// values (NaN, ±Inf) also fall back to "no timeout". Matches the
// Python / napi-rs `Optional<f64>` shape and keeps the same policy
// as [`mesh_run_as_job`] for consistency.
int32_t mesh_job_proxy_wait(struct JobProxyHandle *handle,
                            double timeout_secs,
                            char **out_result_json);

// Request cancellation. The registry forwards the signal to the owner
// replica when alive. `reason` may be NULL.
int32_t mesh_job_proxy_cancel(struct JobProxyHandle *handle, const char *reason);

// Post an event into this job's event channel.
//
// Mirrors [`JobProxy::send_event`]. The running handler (inside a
// `task=true` job) will see the event on its next `recv_event` call —
// or wake immediately if it's currently long-polling.
//
// # Arguments
// - `event_type`: UTF-8 NUL-terminated event-type tag (e.g. `"signal"`,
//   `"user_input"`).
// - `payload_json`: optional UTF-8 NUL-terminated JSON string encoding
//   the event payload. May be `NULL` to send an empty payload (the
//   Rust core treats null/missing as an empty JSON object — matching
//   the Python/TS `payload=None` shape).
// - `out_receipt_json`: receives `*mut c_char` JSON string of the
//   receipt (`{job_id, seq, created_at}`). Caller frees via
//   `mesh_free_string`.
//
// # Returns
// - `0` on success
// - `-1` on invalid args (null handle, malformed payload_json)
// - `-2` on JobNotFound (registry doesn't know the job — 404 from
//   `POST /jobs/{id}/events`). Mapped by the Java SDK to
//   `JobNotFoundException`.
// - `-3` on JobTerminal (job already completed/failed/cancelled — 409
//   from the registry, surfaced as [`JobError::JobTerminal`]). Mapped
//   by the Java SDK to `JobTerminalException`. Distinct from -2 so
//   callers can branch on terminal-state vs. unknown-job.
// - `-4` on other backend errors (transport failure, 5xx after
//   retries, etc.). See `mesh_last_error` for details.
int32_t mesh_job_proxy_send_event(struct JobProxyHandle *handle,
                                  const char *event_type,
                                  const char *payload_json,
                                  char **out_receipt_json);

// Free a [`JobProxyHandle`] returned by [`mesh_submit_job`] /
// [`mesh_job_proxy_new`].
void mesh_job_proxy_free(struct JobProxyHandle *handle);

// Snapshot of the active job context on the current Rust task, or NULL
// if no job is in scope.
//
// Writes a JSON object of shape `{"job_id": str, "deadline_secs_remaining":
// int|null}` to `*out_snapshot_json`. If no context is active, writes NULL
// (same convention as Python's `current_job` returning `None`).
//
// Caller frees the JSON string via `mesh_free_string` if it is non-NULL.
int32_t mesh_current_job(char **out_snapshot_json);

// Compute the `X-Mesh-Job-Id` / `X-Mesh-Timeout` header values for the
// active job context, if any.
//
// Writes a JSON object `{"X-Mesh-Job-Id": "...", "X-Mesh-Timeout":
// "<secs>"}` (with `X-Mesh-Timeout` omitted when no deadline is set) to
// `*out_headers_json`. If no context is active, writes NULL.
//
// Caller frees the JSON string via `mesh_free_string` if it is non-NULL.
int32_t mesh_inject_job_headers(char **out_headers_json);

// Fire the cancel token registered for `job_id` in the process-wide
// cancel registry, if any.
//
// # Returns
// `1` if a token was found and fired, `0` if no active job for that id,
// `-1` on error (null/invalid `job_id`).
int32_t mesh_cancel_active_job(const char *job_id);

// Block until the cancel token bound for `job_id` in the process-wide
// cancel registry fires (explicit cancel via `mesh_cancel_active_job`)
// OR the job is unregistered naturally (ended without cancel — see
// `cancel_registry::JobCancelState::ended`). Resolves immediately if
// the job is not currently registered (already terminal / never claimed).
//
// Returns 0 on success (token resolved or unregistered), -1 on a NULL
// `job_id_ptr` or invalid UTF-8.
//
// Java SDK uses this from a watcher thread (wrapped in a
// `CompletableFuture.runAsync`) to abort outbound OkHttp `Call`s when
// the producer's job is cancelled. The `ended` arm prevents the
// watcher from leaking when the call completes naturally without
// cancel. Mirror of the napi `awaitJobCancel(jobId)` shipped in TS PR
// #897, but blocking instead of async because JNR-FFI doesn't expose
// async return types.
//
// # Safety
// `job_id_ptr` must be a valid C string for the duration of this call.
int32_t mesh_await_job_cancel(const char *job_id_ptr);

// Run a Java-provided callback inside a fresh [`crate::jobs::run_as_job`]
// scope so the cancel-registry entry under the snapshot's `job_id` is
// bound for the duration of the callback (allowing
// `POST /jobs/{id}/cancel` to fire the in-flight cancel token).
//
// `snapshot_json` must encode a JSON object of shape
// `{"job_id": "...", "deadline_secs": <number>|null}` mirroring the
// payload Java SDK constructs from inbound `X-Mesh-Job-Id` / `X-Mesh-Timeout`
// headers. `deadline_secs` is the per-attempt deadline (relative); null /
// missing / non-positive ≡ no deadline.
//
// `callback` is invoked synchronously from the runtime's `block_on`,
// wrapped in [`tokio::task::block_in_place`] so it is legal for the
// callback to issue further blocking FFI calls (e.g.
// `mesh_job_controller_complete` / `_fail` / `_update_progress`) that
// internally re-enter `jobs_runtime().block_on(...)` — without
// `block_in_place` such nested `block_on` calls would panic with
// "Cannot start a runtime from within a runtime". This requires
// `jobs_runtime()` to be a multi-threaded runtime, which it is
// (`Runtime::new()` defaults to `multi_thread`). The callback receives
// the opaque `user_data` pointer the caller passed in. The callback's
// `i32` return value is propagated as this function's return value
// (0 = success, non-zero = caller-defined error).
//
// # Safety
// `callback` must be a valid C function pointer for the entire duration
// of this call. `user_data` is passed through opaquely — Rust does not
// dereference it. If the callback panics across the FFI boundary the
// behaviour is undefined; Java callers must catch all checked / unchecked
// exceptions in their bridge function.
//
// # Caveat
// The Rust `tokio::task_local!` bound by `with_job` is only visible to
// Rust futures polled within the scope. Java code in the callback will
// NOT see the task-local — it must read its own `ThreadLocal` mirror.
// The Rust side handles two things here:
//   1. cancel-registry binding so a `POST /jobs/{id}/cancel` arriving
//      mid-flight fires the in-flight token (the Java SDK reads this via
//      `mesh_cancel_active_job` from its cancel HTTP route);
//   2. header injection on Rust-originated outbound work (the cancel
//      token + `X-Mesh-*` headers are visible to `mesh_call_tool` and
//      friends polled inside the scope).
int32_t mesh_run_as_job(const char *snapshot_json, int32_t (*callback)(void*), void *user_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MCP_MESH_CORE_H */
