apiVersion: v1
kind: Secret
metadata:
  name: mcp-registry-secret
  namespace: mcp-mesh
type: Opaque
stringData:
  # PostgreSQL database credentials - matches Docker test setup
  DATABASE_PASSWORD: "mcpmesh123"

  # Constructed DATABASE_URL for PostgreSQL connection
  DATABASE_URL: "postgres://mcpmesh:mcpmesh123@mcp-mesh-postgres:5432/mcpmesh?sslmode=disable"
