apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-mesh-redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-mesh-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mcp-mesh-redis.selectorLabels" . | nindent 4 }}
