// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"mcp-mesh/src/core/ent/migrate"

	"mcp-mesh/src/core/ent/agent"
	"mcp-mesh/src/core/ent/capability"
	"mcp-mesh/src/core/ent/registryevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Agent is the client for interacting with the Agent builders.
	Agent *AgentClient
	// Capability is the client for interacting with the Capability builders.
	Capability *CapabilityClient
	// RegistryEvent is the client for interacting with the RegistryEvent builders.
	RegistryEvent *RegistryEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Agent = NewAgentClient(c.config)
	c.Capability = NewCapabilityClient(c.config)
	c.RegistryEvent = NewRegistryEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Agent:         NewAgentClient(cfg),
		Capability:    NewCapabilityClient(cfg),
		RegistryEvent: NewRegistryEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Agent:         NewAgentClient(cfg),
		Capability:    NewCapabilityClient(cfg),
		RegistryEvent: NewRegistryEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Agent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Agent.Use(hooks...)
	c.Capability.Use(hooks...)
	c.RegistryEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Agent.Intercept(interceptors...)
	c.Capability.Intercept(interceptors...)
	c.RegistryEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AgentMutation:
		return c.Agent.mutate(ctx, m)
	case *CapabilityMutation:
		return c.Capability.mutate(ctx, m)
	case *RegistryEventMutation:
		return c.RegistryEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AgentClient is a client for the Agent schema.
type AgentClient struct {
	config
}

// NewAgentClient returns a client for the Agent from the given config.
func NewAgentClient(c config) *AgentClient {
	return &AgentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `agent.Hooks(f(g(h())))`.
func (c *AgentClient) Use(hooks ...Hook) {
	c.hooks.Agent = append(c.hooks.Agent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `agent.Intercept(f(g(h())))`.
func (c *AgentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Agent = append(c.inters.Agent, interceptors...)
}

// Create returns a builder for creating a Agent entity.
func (c *AgentClient) Create() *AgentCreate {
	mutation := newAgentMutation(c.config, OpCreate)
	return &AgentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Agent entities.
func (c *AgentClient) CreateBulk(builders ...*AgentCreate) *AgentCreateBulk {
	return &AgentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AgentClient) MapCreateBulk(slice any, setFunc func(*AgentCreate, int)) *AgentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AgentCreateBulk{err: fmt.Errorf("calling to AgentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AgentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AgentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Agent.
func (c *AgentClient) Update() *AgentUpdate {
	mutation := newAgentMutation(c.config, OpUpdate)
	return &AgentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AgentClient) UpdateOne(a *Agent) *AgentUpdateOne {
	mutation := newAgentMutation(c.config, OpUpdateOne, withAgent(a))
	return &AgentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AgentClient) UpdateOneID(id string) *AgentUpdateOne {
	mutation := newAgentMutation(c.config, OpUpdateOne, withAgentID(id))
	return &AgentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Agent.
func (c *AgentClient) Delete() *AgentDelete {
	mutation := newAgentMutation(c.config, OpDelete)
	return &AgentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AgentClient) DeleteOne(a *Agent) *AgentDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AgentClient) DeleteOneID(id string) *AgentDeleteOne {
	builder := c.Delete().Where(agent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AgentDeleteOne{builder}
}

// Query returns a query builder for Agent.
func (c *AgentClient) Query() *AgentQuery {
	return &AgentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAgent},
		inters: c.Interceptors(),
	}
}

// Get returns a Agent entity by its id.
func (c *AgentClient) Get(ctx context.Context, id string) (*Agent, error) {
	return c.Query().Where(agent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AgentClient) GetX(ctx context.Context, id string) *Agent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCapabilities queries the capabilities edge of a Agent.
func (c *AgentClient) QueryCapabilities(a *Agent) *CapabilityQuery {
	query := (&CapabilityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, id),
			sqlgraph.To(capability.Table, capability.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.CapabilitiesTable, agent.CapabilitiesColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Agent.
func (c *AgentClient) QueryEvents(a *Agent) *RegistryEventQuery {
	query := (&RegistryEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, id),
			sqlgraph.To(registryevent.Table, registryevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.EventsTable, agent.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AgentClient) Hooks() []Hook {
	return c.hooks.Agent
}

// Interceptors returns the client interceptors.
func (c *AgentClient) Interceptors() []Interceptor {
	return c.inters.Agent
}

func (c *AgentClient) mutate(ctx context.Context, m *AgentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AgentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AgentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AgentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AgentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Agent mutation op: %q", m.Op())
	}
}

// CapabilityClient is a client for the Capability schema.
type CapabilityClient struct {
	config
}

// NewCapabilityClient returns a client for the Capability from the given config.
func NewCapabilityClient(c config) *CapabilityClient {
	return &CapabilityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `capability.Hooks(f(g(h())))`.
func (c *CapabilityClient) Use(hooks ...Hook) {
	c.hooks.Capability = append(c.hooks.Capability, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `capability.Intercept(f(g(h())))`.
func (c *CapabilityClient) Intercept(interceptors ...Interceptor) {
	c.inters.Capability = append(c.inters.Capability, interceptors...)
}

// Create returns a builder for creating a Capability entity.
func (c *CapabilityClient) Create() *CapabilityCreate {
	mutation := newCapabilityMutation(c.config, OpCreate)
	return &CapabilityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Capability entities.
func (c *CapabilityClient) CreateBulk(builders ...*CapabilityCreate) *CapabilityCreateBulk {
	return &CapabilityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CapabilityClient) MapCreateBulk(slice any, setFunc func(*CapabilityCreate, int)) *CapabilityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CapabilityCreateBulk{err: fmt.Errorf("calling to CapabilityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CapabilityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CapabilityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Capability.
func (c *CapabilityClient) Update() *CapabilityUpdate {
	mutation := newCapabilityMutation(c.config, OpUpdate)
	return &CapabilityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CapabilityClient) UpdateOne(ca *Capability) *CapabilityUpdateOne {
	mutation := newCapabilityMutation(c.config, OpUpdateOne, withCapability(ca))
	return &CapabilityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CapabilityClient) UpdateOneID(id int) *CapabilityUpdateOne {
	mutation := newCapabilityMutation(c.config, OpUpdateOne, withCapabilityID(id))
	return &CapabilityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Capability.
func (c *CapabilityClient) Delete() *CapabilityDelete {
	mutation := newCapabilityMutation(c.config, OpDelete)
	return &CapabilityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CapabilityClient) DeleteOne(ca *Capability) *CapabilityDeleteOne {
	return c.DeleteOneID(ca.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CapabilityClient) DeleteOneID(id int) *CapabilityDeleteOne {
	builder := c.Delete().Where(capability.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CapabilityDeleteOne{builder}
}

// Query returns a query builder for Capability.
func (c *CapabilityClient) Query() *CapabilityQuery {
	return &CapabilityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCapability},
		inters: c.Interceptors(),
	}
}

// Get returns a Capability entity by its id.
func (c *CapabilityClient) Get(ctx context.Context, id int) (*Capability, error) {
	return c.Query().Where(capability.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CapabilityClient) GetX(ctx context.Context, id int) *Capability {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAgent queries the agent edge of a Capability.
func (c *CapabilityClient) QueryAgent(ca *Capability) *AgentQuery {
	query := (&AgentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ca.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(capability.Table, capability.FieldID, id),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, capability.AgentTable, capability.AgentColumn),
		)
		fromV = sqlgraph.Neighbors(ca.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CapabilityClient) Hooks() []Hook {
	return c.hooks.Capability
}

// Interceptors returns the client interceptors.
func (c *CapabilityClient) Interceptors() []Interceptor {
	return c.inters.Capability
}

func (c *CapabilityClient) mutate(ctx context.Context, m *CapabilityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CapabilityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CapabilityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CapabilityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CapabilityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Capability mutation op: %q", m.Op())
	}
}

// RegistryEventClient is a client for the RegistryEvent schema.
type RegistryEventClient struct {
	config
}

// NewRegistryEventClient returns a client for the RegistryEvent from the given config.
func NewRegistryEventClient(c config) *RegistryEventClient {
	return &RegistryEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `registryevent.Hooks(f(g(h())))`.
func (c *RegistryEventClient) Use(hooks ...Hook) {
	c.hooks.RegistryEvent = append(c.hooks.RegistryEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `registryevent.Intercept(f(g(h())))`.
func (c *RegistryEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.RegistryEvent = append(c.inters.RegistryEvent, interceptors...)
}

// Create returns a builder for creating a RegistryEvent entity.
func (c *RegistryEventClient) Create() *RegistryEventCreate {
	mutation := newRegistryEventMutation(c.config, OpCreate)
	return &RegistryEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RegistryEvent entities.
func (c *RegistryEventClient) CreateBulk(builders ...*RegistryEventCreate) *RegistryEventCreateBulk {
	return &RegistryEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RegistryEventClient) MapCreateBulk(slice any, setFunc func(*RegistryEventCreate, int)) *RegistryEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RegistryEventCreateBulk{err: fmt.Errorf("calling to RegistryEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RegistryEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RegistryEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RegistryEvent.
func (c *RegistryEventClient) Update() *RegistryEventUpdate {
	mutation := newRegistryEventMutation(c.config, OpUpdate)
	return &RegistryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RegistryEventClient) UpdateOne(re *RegistryEvent) *RegistryEventUpdateOne {
	mutation := newRegistryEventMutation(c.config, OpUpdateOne, withRegistryEvent(re))
	return &RegistryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RegistryEventClient) UpdateOneID(id int) *RegistryEventUpdateOne {
	mutation := newRegistryEventMutation(c.config, OpUpdateOne, withRegistryEventID(id))
	return &RegistryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RegistryEvent.
func (c *RegistryEventClient) Delete() *RegistryEventDelete {
	mutation := newRegistryEventMutation(c.config, OpDelete)
	return &RegistryEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RegistryEventClient) DeleteOne(re *RegistryEvent) *RegistryEventDeleteOne {
	return c.DeleteOneID(re.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RegistryEventClient) DeleteOneID(id int) *RegistryEventDeleteOne {
	builder := c.Delete().Where(registryevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RegistryEventDeleteOne{builder}
}

// Query returns a query builder for RegistryEvent.
func (c *RegistryEventClient) Query() *RegistryEventQuery {
	return &RegistryEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRegistryEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a RegistryEvent entity by its id.
func (c *RegistryEventClient) Get(ctx context.Context, id int) (*RegistryEvent, error) {
	return c.Query().Where(registryevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RegistryEventClient) GetX(ctx context.Context, id int) *RegistryEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAgent queries the agent edge of a RegistryEvent.
func (c *RegistryEventClient) QueryAgent(re *RegistryEvent) *AgentQuery {
	query := (&AgentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := re.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(registryevent.Table, registryevent.FieldID, id),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, registryevent.AgentTable, registryevent.AgentColumn),
		)
		fromV = sqlgraph.Neighbors(re.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RegistryEventClient) Hooks() []Hook {
	return c.hooks.RegistryEvent
}

// Interceptors returns the client interceptors.
func (c *RegistryEventClient) Interceptors() []Interceptor {
	return c.inters.RegistryEvent
}

func (c *RegistryEventClient) mutate(ctx context.Context, m *RegistryEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RegistryEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RegistryEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RegistryEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RegistryEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RegistryEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Agent, Capability, RegistryEvent []ent.Hook
	}
	inters struct {
		Agent, Capability, RegistryEvent []ent.Interceptor
	}
)
