// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mcp-mesh/src/core/ent/jobevent"
	"mcp-mesh/src/core/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobEventDelete is the builder for deleting a JobEvent entity.
type JobEventDelete struct {
	config
	hooks    []Hook
	mutation *JobEventMutation
}

// Where appends a list predicates to the JobEventDelete builder.
func (jed *JobEventDelete) Where(ps ...predicate.JobEvent) *JobEventDelete {
	jed.mutation.Where(ps...)
	return jed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jed *JobEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jed.sqlExec, jed.mutation, jed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jed *JobEventDelete) ExecX(ctx context.Context) int {
	n, err := jed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jed *JobEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jobevent.Table, sqlgraph.NewFieldSpec(jobevent.FieldID, field.TypeInt))
	if ps := jed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jed.mutation.done = true
	return affected, err
}

// JobEventDeleteOne is the builder for deleting a single JobEvent entity.
type JobEventDeleteOne struct {
	jed *JobEventDelete
}

// Where appends a list predicates to the JobEventDelete builder.
func (jedo *JobEventDeleteOne) Where(ps ...predicate.JobEvent) *JobEventDeleteOne {
	jedo.jed.mutation.Where(ps...)
	return jedo
}

// Exec executes the deletion query.
func (jedo *JobEventDeleteOne) Exec(ctx context.Context) error {
	n, err := jedo.jed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jedo *JobEventDeleteOne) ExecX(ctx context.Context) {
	if err := jedo.Exec(ctx); err != nil {
		panic(err)
	}
}
