// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcp-mesh/src/core/ent/jobevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobEventCreate is the builder for creating a JobEvent entity.
type JobEventCreate struct {
	config
	mutation *JobEventMutation
	hooks    []Hook
}

// SetSeq sets the "seq" field.
func (jec *JobEventCreate) SetSeq(i int64) *JobEventCreate {
	jec.mutation.SetSeq(i)
	return jec
}

// SetJobID sets the "job_id" field.
func (jec *JobEventCreate) SetJobID(s string) *JobEventCreate {
	jec.mutation.SetJobID(s)
	return jec
}

// SetType sets the "type" field.
func (jec *JobEventCreate) SetType(s string) *JobEventCreate {
	jec.mutation.SetType(s)
	return jec
}

// SetPayload sets the "payload" field.
func (jec *JobEventCreate) SetPayload(m map[string]interface{}) *JobEventCreate {
	jec.mutation.SetPayload(m)
	return jec
}

// SetTraceContext sets the "trace_context" field.
func (jec *JobEventCreate) SetTraceContext(m map[string]interface{}) *JobEventCreate {
	jec.mutation.SetTraceContext(m)
	return jec
}

// SetPostedBy sets the "posted_by" field.
func (jec *JobEventCreate) SetPostedBy(s string) *JobEventCreate {
	jec.mutation.SetPostedBy(s)
	return jec
}

// SetNillablePostedBy sets the "posted_by" field if the given value is not nil.
func (jec *JobEventCreate) SetNillablePostedBy(s *string) *JobEventCreate {
	if s != nil {
		jec.SetPostedBy(*s)
	}
	return jec
}

// SetCreatedAt sets the "created_at" field.
func (jec *JobEventCreate) SetCreatedAt(t time.Time) *JobEventCreate {
	jec.mutation.SetCreatedAt(t)
	return jec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jec *JobEventCreate) SetNillableCreatedAt(t *time.Time) *JobEventCreate {
	if t != nil {
		jec.SetCreatedAt(*t)
	}
	return jec
}

// Mutation returns the JobEventMutation object of the builder.
func (jec *JobEventCreate) Mutation() *JobEventMutation {
	return jec.mutation
}

// Save creates the JobEvent in the database.
func (jec *JobEventCreate) Save(ctx context.Context) (*JobEvent, error) {
	jec.defaults()
	return withHooks(ctx, jec.sqlSave, jec.mutation, jec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jec *JobEventCreate) SaveX(ctx context.Context) *JobEvent {
	v, err := jec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jec *JobEventCreate) Exec(ctx context.Context) error {
	_, err := jec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jec *JobEventCreate) ExecX(ctx context.Context) {
	if err := jec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jec *JobEventCreate) defaults() {
	if _, ok := jec.mutation.CreatedAt(); !ok {
		v := jobevent.DefaultCreatedAt()
		jec.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jec *JobEventCreate) check() error {
	if _, ok := jec.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "JobEvent.seq"`)}
	}
	if _, ok := jec.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "JobEvent.job_id"`)}
	}
	if v, ok := jec.mutation.JobID(); ok {
		if err := jobevent.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "JobEvent.job_id": %w`, err)}
		}
	}
	if _, ok := jec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "JobEvent.type"`)}
	}
	if v, ok := jec.mutation.GetType(); ok {
		if err := jobevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "JobEvent.type": %w`, err)}
		}
	}
	if _, ok := jec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "JobEvent.created_at"`)}
	}
	return nil
}

func (jec *JobEventCreate) sqlSave(ctx context.Context) (*JobEvent, error) {
	if err := jec.check(); err != nil {
		return nil, err
	}
	_node, _spec := jec.createSpec()
	if err := sqlgraph.CreateNode(ctx, jec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	jec.mutation.id = &_node.ID
	jec.mutation.done = true
	return _node, nil
}

func (jec *JobEventCreate) createSpec() (*JobEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &JobEvent{config: jec.config}
		_spec = sqlgraph.NewCreateSpec(jobevent.Table, sqlgraph.NewFieldSpec(jobevent.FieldID, field.TypeInt))
	)
	if value, ok := jec.mutation.Seq(); ok {
		_spec.SetField(jobevent.FieldSeq, field.TypeInt64, value)
		_node.Seq = value
	}
	if value, ok := jec.mutation.JobID(); ok {
		_spec.SetField(jobevent.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := jec.mutation.GetType(); ok {
		_spec.SetField(jobevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := jec.mutation.Payload(); ok {
		_spec.SetField(jobevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := jec.mutation.TraceContext(); ok {
		_spec.SetField(jobevent.FieldTraceContext, field.TypeJSON, value)
		_node.TraceContext = value
	}
	if value, ok := jec.mutation.PostedBy(); ok {
		_spec.SetField(jobevent.FieldPostedBy, field.TypeString, value)
		_node.PostedBy = &value
	}
	if value, ok := jec.mutation.CreatedAt(); ok {
		_spec.SetField(jobevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// JobEventCreateBulk is the builder for creating many JobEvent entities in bulk.
type JobEventCreateBulk struct {
	config
	err      error
	builders []*JobEventCreate
}

// Save creates the JobEvent entities in the database.
func (jecb *JobEventCreateBulk) Save(ctx context.Context) ([]*JobEvent, error) {
	if jecb.err != nil {
		return nil, jecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jecb.builders))
	nodes := make([]*JobEvent, len(jecb.builders))
	mutators := make([]Mutator, len(jecb.builders))
	for i := range jecb.builders {
		func(i int, root context.Context) {
			builder := jecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jecb *JobEventCreateBulk) SaveX(ctx context.Context) []*JobEvent {
	v, err := jecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jecb *JobEventCreateBulk) Exec(ctx context.Context) error {
	_, err := jecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jecb *JobEventCreateBulk) ExecX(ctx context.Context) {
	if err := jecb.Exec(ctx); err != nil {
		panic(err)
	}
}
