// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"mcp-mesh/src/core/ent/agent"
	"mcp-mesh/src/core/ent/llmproviderresolution"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LLMProviderResolution is the model entity for the LLMProviderResolution schema.
type LLMProviderResolution struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Agent ID that has the @mesh.llm decorated function
	ConsumerAgentID string `json:"consumer_agent_id,omitempty"`
	// Function/tool name with @mesh.llm decorator
	ConsumerFunctionName string `json:"consumer_function_name,omitempty"`
	// Required capability (e.g., 'llm')
	RequiredCapability string `json:"required_capability,omitempty"`
	// Required tags for smart matching (e.g., ['llm', '+claude'])
	RequiredTags []string `json:"required_tags,omitempty"`
	// Version constraint (e.g., '>=1.0.0')
	RequiredVersion *string `json:"required_version,omitempty"`
	// Required namespace
	RequiredNamespace string `json:"required_namespace,omitempty"`
	// Agent ID providing LLM capability (NULL if unresolved)
	ProviderAgentID *string `json:"provider_agent_id,omitempty"`
	// MCP tool/function name on provider agent (e.g., 'llm')
	ProviderFunctionName *string `json:"provider_function_name,omitempty"`
	// Provider endpoint URL
	Endpoint *string `json:"endpoint,omitempty"`
	// Provider resolution status
	Status llmproviderresolution.Status `json:"status,omitempty"`
	// When this provider was last successfully resolved
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LLMProviderResolutionQuery when eager-loading is set.
	Edges        LLMProviderResolutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LLMProviderResolutionEdges holds the relations/edges for other nodes in the graph.
type LLMProviderResolutionEdges struct {
	// Agent that has the @mesh.llm function
	ConsumerAgent *Agent `json:"consumer_agent,omitempty"`
	// Agent that provides LLM capability (nullable)
	ProviderAgent *Agent `json:"provider_agent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ConsumerAgentOrErr returns the ConsumerAgent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LLMProviderResolutionEdges) ConsumerAgentOrErr() (*Agent, error) {
	if e.ConsumerAgent != nil {
		return e.ConsumerAgent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "consumer_agent"}
}

// ProviderAgentOrErr returns the ProviderAgent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LLMProviderResolutionEdges) ProviderAgentOrErr() (*Agent, error) {
	if e.ProviderAgent != nil {
		return e.ProviderAgent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "provider_agent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LLMProviderResolution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case llmproviderresolution.FieldRequiredTags:
			values[i] = new([]byte)
		case llmproviderresolution.FieldID:
			values[i] = new(sql.NullInt64)
		case llmproviderresolution.FieldConsumerAgentID, llmproviderresolution.FieldConsumerFunctionName, llmproviderresolution.FieldRequiredCapability, llmproviderresolution.FieldRequiredVersion, llmproviderresolution.FieldRequiredNamespace, llmproviderresolution.FieldProviderAgentID, llmproviderresolution.FieldProviderFunctionName, llmproviderresolution.FieldEndpoint, llmproviderresolution.FieldStatus:
			values[i] = new(sql.NullString)
		case llmproviderresolution.FieldResolvedAt, llmproviderresolution.FieldCreatedAt, llmproviderresolution.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LLMProviderResolution fields.
func (lpr *LLMProviderResolution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case llmproviderresolution.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lpr.ID = int(value.Int64)
		case llmproviderresolution.FieldConsumerAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_agent_id", values[i])
			} else if value.Valid {
				lpr.ConsumerAgentID = value.String
			}
		case llmproviderresolution.FieldConsumerFunctionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_function_name", values[i])
			} else if value.Valid {
				lpr.ConsumerFunctionName = value.String
			}
		case llmproviderresolution.FieldRequiredCapability:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field required_capability", values[i])
			} else if value.Valid {
				lpr.RequiredCapability = value.String
			}
		case llmproviderresolution.FieldRequiredTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field required_tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &lpr.RequiredTags); err != nil {
					return fmt.Errorf("unmarshal field required_tags: %w", err)
				}
			}
		case llmproviderresolution.FieldRequiredVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field required_version", values[i])
			} else if value.Valid {
				lpr.RequiredVersion = new(string)
				*lpr.RequiredVersion = value.String
			}
		case llmproviderresolution.FieldRequiredNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field required_namespace", values[i])
			} else if value.Valid {
				lpr.RequiredNamespace = value.String
			}
		case llmproviderresolution.FieldProviderAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_agent_id", values[i])
			} else if value.Valid {
				lpr.ProviderAgentID = new(string)
				*lpr.ProviderAgentID = value.String
			}
		case llmproviderresolution.FieldProviderFunctionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_function_name", values[i])
			} else if value.Valid {
				lpr.ProviderFunctionName = new(string)
				*lpr.ProviderFunctionName = value.String
			}
		case llmproviderresolution.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				lpr.Endpoint = new(string)
				*lpr.Endpoint = value.String
			}
		case llmproviderresolution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				lpr.Status = llmproviderresolution.Status(value.String)
			}
		case llmproviderresolution.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				lpr.ResolvedAt = new(time.Time)
				*lpr.ResolvedAt = value.Time
			}
		case llmproviderresolution.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				lpr.CreatedAt = value.Time
			}
		case llmproviderresolution.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				lpr.UpdatedAt = value.Time
			}
		default:
			lpr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LLMProviderResolution.
// This includes values selected through modifiers, order, etc.
func (lpr *LLMProviderResolution) Value(name string) (ent.Value, error) {
	return lpr.selectValues.Get(name)
}

// QueryConsumerAgent queries the "consumer_agent" edge of the LLMProviderResolution entity.
func (lpr *LLMProviderResolution) QueryConsumerAgent() *AgentQuery {
	return NewLLMProviderResolutionClient(lpr.config).QueryConsumerAgent(lpr)
}

// QueryProviderAgent queries the "provider_agent" edge of the LLMProviderResolution entity.
func (lpr *LLMProviderResolution) QueryProviderAgent() *AgentQuery {
	return NewLLMProviderResolutionClient(lpr.config).QueryProviderAgent(lpr)
}

// Update returns a builder for updating this LLMProviderResolution.
// Note that you need to call LLMProviderResolution.Unwrap() before calling this method if this LLMProviderResolution
// was returned from a transaction, and the transaction was committed or rolled back.
func (lpr *LLMProviderResolution) Update() *LLMProviderResolutionUpdateOne {
	return NewLLMProviderResolutionClient(lpr.config).UpdateOne(lpr)
}

// Unwrap unwraps the LLMProviderResolution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lpr *LLMProviderResolution) Unwrap() *LLMProviderResolution {
	_tx, ok := lpr.config.driver.(*txDriver)
	if !ok {
		panic("ent: LLMProviderResolution is not a transactional entity")
	}
	lpr.config.driver = _tx.drv
	return lpr
}

// String implements the fmt.Stringer.
func (lpr *LLMProviderResolution) String() string {
	var builder strings.Builder
	builder.WriteString("LLMProviderResolution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lpr.ID))
	builder.WriteString("consumer_agent_id=")
	builder.WriteString(lpr.ConsumerAgentID)
	builder.WriteString(", ")
	builder.WriteString("consumer_function_name=")
	builder.WriteString(lpr.ConsumerFunctionName)
	builder.WriteString(", ")
	builder.WriteString("required_capability=")
	builder.WriteString(lpr.RequiredCapability)
	builder.WriteString(", ")
	builder.WriteString("required_tags=")
	builder.WriteString(fmt.Sprintf("%v", lpr.RequiredTags))
	builder.WriteString(", ")
	if v := lpr.RequiredVersion; v != nil {
		builder.WriteString("required_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("required_namespace=")
	builder.WriteString(lpr.RequiredNamespace)
	builder.WriteString(", ")
	if v := lpr.ProviderAgentID; v != nil {
		builder.WriteString("provider_agent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := lpr.ProviderFunctionName; v != nil {
		builder.WriteString("provider_function_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := lpr.Endpoint; v != nil {
		builder.WriteString("endpoint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", lpr.Status))
	builder.WriteString(", ")
	if v := lpr.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(lpr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(lpr.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LLMProviderResolutions is a parsable slice of LLMProviderResolution.
type LLMProviderResolutions []*LLMProviderResolution
