// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcp-mesh/src/core/ent/agent"
	"mcp-mesh/src/core/ent/llmtoolresolution"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LLMToolResolutionCreate is the builder for creating a LLMToolResolution entity.
type LLMToolResolutionCreate struct {
	config
	mutation *LLMToolResolutionMutation
	hooks    []Hook
}

// SetConsumerAgentID sets the "consumer_agent_id" field.
func (ltrc *LLMToolResolutionCreate) SetConsumerAgentID(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetConsumerAgentID(s)
	return ltrc
}

// SetConsumerFunctionName sets the "consumer_function_name" field.
func (ltrc *LLMToolResolutionCreate) SetConsumerFunctionName(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetConsumerFunctionName(s)
	return ltrc
}

// SetFilterCapability sets the "filter_capability" field.
func (ltrc *LLMToolResolutionCreate) SetFilterCapability(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetFilterCapability(s)
	return ltrc
}

// SetNillableFilterCapability sets the "filter_capability" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableFilterCapability(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetFilterCapability(*s)
	}
	return ltrc
}

// SetFilterTags sets the "filter_tags" field.
func (ltrc *LLMToolResolutionCreate) SetFilterTags(s []string) *LLMToolResolutionCreate {
	ltrc.mutation.SetFilterTags(s)
	return ltrc
}

// SetFilterMode sets the "filter_mode" field.
func (ltrc *LLMToolResolutionCreate) SetFilterMode(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetFilterMode(s)
	return ltrc
}

// SetNillableFilterMode sets the "filter_mode" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableFilterMode(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetFilterMode(*s)
	}
	return ltrc
}

// SetProviderAgentID sets the "provider_agent_id" field.
func (ltrc *LLMToolResolutionCreate) SetProviderAgentID(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetProviderAgentID(s)
	return ltrc
}

// SetNillableProviderAgentID sets the "provider_agent_id" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableProviderAgentID(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetProviderAgentID(*s)
	}
	return ltrc
}

// SetProviderFunctionName sets the "provider_function_name" field.
func (ltrc *LLMToolResolutionCreate) SetProviderFunctionName(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetProviderFunctionName(s)
	return ltrc
}

// SetNillableProviderFunctionName sets the "provider_function_name" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableProviderFunctionName(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetProviderFunctionName(*s)
	}
	return ltrc
}

// SetProviderCapability sets the "provider_capability" field.
func (ltrc *LLMToolResolutionCreate) SetProviderCapability(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetProviderCapability(s)
	return ltrc
}

// SetNillableProviderCapability sets the "provider_capability" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableProviderCapability(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetProviderCapability(*s)
	}
	return ltrc
}

// SetEndpoint sets the "endpoint" field.
func (ltrc *LLMToolResolutionCreate) SetEndpoint(s string) *LLMToolResolutionCreate {
	ltrc.mutation.SetEndpoint(s)
	return ltrc
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableEndpoint(s *string) *LLMToolResolutionCreate {
	if s != nil {
		ltrc.SetEndpoint(*s)
	}
	return ltrc
}

// SetStatus sets the "status" field.
func (ltrc *LLMToolResolutionCreate) SetStatus(l llmtoolresolution.Status) *LLMToolResolutionCreate {
	ltrc.mutation.SetStatus(l)
	return ltrc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableStatus(l *llmtoolresolution.Status) *LLMToolResolutionCreate {
	if l != nil {
		ltrc.SetStatus(*l)
	}
	return ltrc
}

// SetResolvedAt sets the "resolved_at" field.
func (ltrc *LLMToolResolutionCreate) SetResolvedAt(t time.Time) *LLMToolResolutionCreate {
	ltrc.mutation.SetResolvedAt(t)
	return ltrc
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableResolvedAt(t *time.Time) *LLMToolResolutionCreate {
	if t != nil {
		ltrc.SetResolvedAt(*t)
	}
	return ltrc
}

// SetCreatedAt sets the "created_at" field.
func (ltrc *LLMToolResolutionCreate) SetCreatedAt(t time.Time) *LLMToolResolutionCreate {
	ltrc.mutation.SetCreatedAt(t)
	return ltrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableCreatedAt(t *time.Time) *LLMToolResolutionCreate {
	if t != nil {
		ltrc.SetCreatedAt(*t)
	}
	return ltrc
}

// SetUpdatedAt sets the "updated_at" field.
func (ltrc *LLMToolResolutionCreate) SetUpdatedAt(t time.Time) *LLMToolResolutionCreate {
	ltrc.mutation.SetUpdatedAt(t)
	return ltrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ltrc *LLMToolResolutionCreate) SetNillableUpdatedAt(t *time.Time) *LLMToolResolutionCreate {
	if t != nil {
		ltrc.SetUpdatedAt(*t)
	}
	return ltrc
}

// SetConsumerAgent sets the "consumer_agent" edge to the Agent entity.
func (ltrc *LLMToolResolutionCreate) SetConsumerAgent(a *Agent) *LLMToolResolutionCreate {
	return ltrc.SetConsumerAgentID(a.ID)
}

// SetProviderAgent sets the "provider_agent" edge to the Agent entity.
func (ltrc *LLMToolResolutionCreate) SetProviderAgent(a *Agent) *LLMToolResolutionCreate {
	return ltrc.SetProviderAgentID(a.ID)
}

// Mutation returns the LLMToolResolutionMutation object of the builder.
func (ltrc *LLMToolResolutionCreate) Mutation() *LLMToolResolutionMutation {
	return ltrc.mutation
}

// Save creates the LLMToolResolution in the database.
func (ltrc *LLMToolResolutionCreate) Save(ctx context.Context) (*LLMToolResolution, error) {
	ltrc.defaults()
	return withHooks(ctx, ltrc.sqlSave, ltrc.mutation, ltrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ltrc *LLMToolResolutionCreate) SaveX(ctx context.Context) *LLMToolResolution {
	v, err := ltrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltrc *LLMToolResolutionCreate) Exec(ctx context.Context) error {
	_, err := ltrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltrc *LLMToolResolutionCreate) ExecX(ctx context.Context) {
	if err := ltrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ltrc *LLMToolResolutionCreate) defaults() {
	if _, ok := ltrc.mutation.FilterMode(); !ok {
		v := llmtoolresolution.DefaultFilterMode
		ltrc.mutation.SetFilterMode(v)
	}
	if _, ok := ltrc.mutation.Status(); !ok {
		v := llmtoolresolution.DefaultStatus
		ltrc.mutation.SetStatus(v)
	}
	if _, ok := ltrc.mutation.CreatedAt(); !ok {
		v := llmtoolresolution.DefaultCreatedAt()
		ltrc.mutation.SetCreatedAt(v)
	}
	if _, ok := ltrc.mutation.UpdatedAt(); !ok {
		v := llmtoolresolution.DefaultUpdatedAt()
		ltrc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ltrc *LLMToolResolutionCreate) check() error {
	if _, ok := ltrc.mutation.ConsumerAgentID(); !ok {
		return &ValidationError{Name: "consumer_agent_id", err: errors.New(`ent: missing required field "LLMToolResolution.consumer_agent_id"`)}
	}
	if _, ok := ltrc.mutation.ConsumerFunctionName(); !ok {
		return &ValidationError{Name: "consumer_function_name", err: errors.New(`ent: missing required field "LLMToolResolution.consumer_function_name"`)}
	}
	if _, ok := ltrc.mutation.FilterMode(); !ok {
		return &ValidationError{Name: "filter_mode", err: errors.New(`ent: missing required field "LLMToolResolution.filter_mode"`)}
	}
	if _, ok := ltrc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LLMToolResolution.status"`)}
	}
	if v, ok := ltrc.mutation.Status(); ok {
		if err := llmtoolresolution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LLMToolResolution.status": %w`, err)}
		}
	}
	if _, ok := ltrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LLMToolResolution.created_at"`)}
	}
	if _, ok := ltrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LLMToolResolution.updated_at"`)}
	}
	if len(ltrc.mutation.ConsumerAgentIDs()) == 0 {
		return &ValidationError{Name: "consumer_agent", err: errors.New(`ent: missing required edge "LLMToolResolution.consumer_agent"`)}
	}
	return nil
}

func (ltrc *LLMToolResolutionCreate) sqlSave(ctx context.Context) (*LLMToolResolution, error) {
	if err := ltrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ltrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ltrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ltrc.mutation.id = &_node.ID
	ltrc.mutation.done = true
	return _node, nil
}

func (ltrc *LLMToolResolutionCreate) createSpec() (*LLMToolResolution, *sqlgraph.CreateSpec) {
	var (
		_node = &LLMToolResolution{config: ltrc.config}
		_spec = sqlgraph.NewCreateSpec(llmtoolresolution.Table, sqlgraph.NewFieldSpec(llmtoolresolution.FieldID, field.TypeInt))
	)
	if value, ok := ltrc.mutation.ConsumerFunctionName(); ok {
		_spec.SetField(llmtoolresolution.FieldConsumerFunctionName, field.TypeString, value)
		_node.ConsumerFunctionName = value
	}
	if value, ok := ltrc.mutation.FilterCapability(); ok {
		_spec.SetField(llmtoolresolution.FieldFilterCapability, field.TypeString, value)
		_node.FilterCapability = &value
	}
	if value, ok := ltrc.mutation.FilterTags(); ok {
		_spec.SetField(llmtoolresolution.FieldFilterTags, field.TypeJSON, value)
		_node.FilterTags = value
	}
	if value, ok := ltrc.mutation.FilterMode(); ok {
		_spec.SetField(llmtoolresolution.FieldFilterMode, field.TypeString, value)
		_node.FilterMode = value
	}
	if value, ok := ltrc.mutation.ProviderFunctionName(); ok {
		_spec.SetField(llmtoolresolution.FieldProviderFunctionName, field.TypeString, value)
		_node.ProviderFunctionName = &value
	}
	if value, ok := ltrc.mutation.ProviderCapability(); ok {
		_spec.SetField(llmtoolresolution.FieldProviderCapability, field.TypeString, value)
		_node.ProviderCapability = &value
	}
	if value, ok := ltrc.mutation.Endpoint(); ok {
		_spec.SetField(llmtoolresolution.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = &value
	}
	if value, ok := ltrc.mutation.Status(); ok {
		_spec.SetField(llmtoolresolution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ltrc.mutation.ResolvedAt(); ok {
		_spec.SetField(llmtoolresolution.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := ltrc.mutation.CreatedAt(); ok {
		_spec.SetField(llmtoolresolution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ltrc.mutation.UpdatedAt(); ok {
		_spec.SetField(llmtoolresolution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ltrc.mutation.ConsumerAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   llmtoolresolution.ConsumerAgentTable,
			Columns: []string{llmtoolresolution.ConsumerAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConsumerAgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ltrc.mutation.ProviderAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   llmtoolresolution.ProviderAgentTable,
			Columns: []string{llmtoolresolution.ProviderAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderAgentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LLMToolResolutionCreateBulk is the builder for creating many LLMToolResolution entities in bulk.
type LLMToolResolutionCreateBulk struct {
	config
	err      error
	builders []*LLMToolResolutionCreate
}

// Save creates the LLMToolResolution entities in the database.
func (ltrcb *LLMToolResolutionCreateBulk) Save(ctx context.Context) ([]*LLMToolResolution, error) {
	if ltrcb.err != nil {
		return nil, ltrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ltrcb.builders))
	nodes := make([]*LLMToolResolution, len(ltrcb.builders))
	mutators := make([]Mutator, len(ltrcb.builders))
	for i := range ltrcb.builders {
		func(i int, root context.Context) {
			builder := ltrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LLMToolResolutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ltrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ltrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ltrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ltrcb *LLMToolResolutionCreateBulk) SaveX(ctx context.Context) []*LLMToolResolution {
	v, err := ltrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltrcb *LLMToolResolutionCreateBulk) Exec(ctx context.Context) error {
	_, err := ltrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltrcb *LLMToolResolutionCreateBulk) ExecX(ctx context.Context) {
	if err := ltrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
