// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mcp-mesh/src/core/ent/predicate"
	"mcp-mesh/src/core/ent/registryevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RegistryEventDelete is the builder for deleting a RegistryEvent entity.
type RegistryEventDelete struct {
	config
	hooks    []Hook
	mutation *RegistryEventMutation
}

// Where appends a list predicates to the RegistryEventDelete builder.
func (red *RegistryEventDelete) Where(ps ...predicate.RegistryEvent) *RegistryEventDelete {
	red.mutation.Where(ps...)
	return red
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (red *RegistryEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, red.sqlExec, red.mutation, red.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (red *RegistryEventDelete) ExecX(ctx context.Context) int {
	n, err := red.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (red *RegistryEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(registryevent.Table, sqlgraph.NewFieldSpec(registryevent.FieldID, field.TypeInt))
	if ps := red.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, red.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	red.mutation.done = true
	return affected, err
}

// RegistryEventDeleteOne is the builder for deleting a single RegistryEvent entity.
type RegistryEventDeleteOne struct {
	red *RegistryEventDelete
}

// Where appends a list predicates to the RegistryEventDelete builder.
func (redo *RegistryEventDeleteOne) Where(ps ...predicate.RegistryEvent) *RegistryEventDeleteOne {
	redo.red.mutation.Where(ps...)
	return redo
}

// Exec executes the deletion query.
func (redo *RegistryEventDeleteOne) Exec(ctx context.Context) error {
	n, err := redo.red.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{registryevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (redo *RegistryEventDeleteOne) ExecX(ctx context.Context) {
	if err := redo.Exec(ctx); err != nil {
		panic(err)
	}
}
