// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mcp-mesh/src/core/ent/agent"
	"mcp-mesh/src/core/ent/capability"
	"mcp-mesh/src/core/ent/registryevent"
	"mcp-mesh/src/core/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescNamespace is the schema descriptor for namespace field.
	agentDescNamespace := agentFields[6].Descriptor()
	// agent.DefaultNamespace holds the default value on creation for the namespace field.
	agent.DefaultNamespace = agentDescNamespace.Default.(string)
	// agentDescTotalDependencies is the schema descriptor for total_dependencies field.
	agentDescTotalDependencies := agentFields[7].Descriptor()
	// agent.DefaultTotalDependencies holds the default value on creation for the total_dependencies field.
	agent.DefaultTotalDependencies = agentDescTotalDependencies.Default.(int)
	// agentDescDependenciesResolved is the schema descriptor for dependencies_resolved field.
	agentDescDependenciesResolved := agentFields[8].Descriptor()
	// agent.DefaultDependenciesResolved holds the default value on creation for the dependencies_resolved field.
	agent.DefaultDependenciesResolved = agentDescDependenciesResolved.Default.(int)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[9].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentFields[10].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	capabilityFields := schema.Capability{}.Fields()
	_ = capabilityFields
	// capabilityDescVersion is the schema descriptor for version field.
	capabilityDescVersion := capabilityFields[2].Descriptor()
	// capability.DefaultVersion holds the default value on creation for the version field.
	capability.DefaultVersion = capabilityDescVersion.Default.(string)
	// capabilityDescTags is the schema descriptor for tags field.
	capabilityDescTags := capabilityFields[4].Descriptor()
	// capability.DefaultTags holds the default value on creation for the tags field.
	capability.DefaultTags = capabilityDescTags.Default.([]string)
	// capabilityDescCreatedAt is the schema descriptor for created_at field.
	capabilityDescCreatedAt := capabilityFields[5].Descriptor()
	// capability.DefaultCreatedAt holds the default value on creation for the created_at field.
	capability.DefaultCreatedAt = capabilityDescCreatedAt.Default.(func() time.Time)
	// capabilityDescUpdatedAt is the schema descriptor for updated_at field.
	capabilityDescUpdatedAt := capabilityFields[6].Descriptor()
	// capability.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	capability.DefaultUpdatedAt = capabilityDescUpdatedAt.Default.(func() time.Time)
	// capability.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	capability.UpdateDefaultUpdatedAt = capabilityDescUpdatedAt.UpdateDefault.(func() time.Time)
	registryeventFields := schema.RegistryEvent{}.Fields()
	_ = registryeventFields
	// registryeventDescTimestamp is the schema descriptor for timestamp field.
	registryeventDescTimestamp := registryeventFields[2].Descriptor()
	// registryevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	registryevent.DefaultTimestamp = registryeventDescTimestamp.Default.(func() time.Time)
	// registryeventDescData is the schema descriptor for data field.
	registryeventDescData := registryeventFields[3].Descriptor()
	// registryevent.DefaultData holds the default value on creation for the data field.
	registryevent.DefaultData = registryeventDescData.Default.(map[string]interface{})
}
