// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mcp-mesh/src/core/ent/predicate"
	"mcp-mesh/src/core/ent/schemaentry"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaEntryDelete is the builder for deleting a SchemaEntry entity.
type SchemaEntryDelete struct {
	config
	hooks    []Hook
	mutation *SchemaEntryMutation
}

// Where appends a list predicates to the SchemaEntryDelete builder.
func (sed *SchemaEntryDelete) Where(ps ...predicate.SchemaEntry) *SchemaEntryDelete {
	sed.mutation.Where(ps...)
	return sed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sed *SchemaEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sed.sqlExec, sed.mutation, sed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sed *SchemaEntryDelete) ExecX(ctx context.Context) int {
	n, err := sed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sed *SchemaEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(schemaentry.Table, sqlgraph.NewFieldSpec(schemaentry.FieldID, field.TypeInt))
	if ps := sed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sed.mutation.done = true
	return affected, err
}

// SchemaEntryDeleteOne is the builder for deleting a single SchemaEntry entity.
type SchemaEntryDeleteOne struct {
	sed *SchemaEntryDelete
}

// Where appends a list predicates to the SchemaEntryDelete builder.
func (sedo *SchemaEntryDeleteOne) Where(ps ...predicate.SchemaEntry) *SchemaEntryDeleteOne {
	sedo.sed.mutation.Where(ps...)
	return sedo
}

// Exec executes the deletion query.
func (sedo *SchemaEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := sedo.sed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{schemaentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sedo *SchemaEntryDeleteOne) ExecX(ctx context.Context) {
	if err := sedo.Exec(ctx); err != nil {
		panic(err)
	}
}
