// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mcp-mesh/src/core/ent/predicate"
	"mcp-mesh/src/core/ent/schemaentry"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaEntryUpdate is the builder for updating SchemaEntry entities.
type SchemaEntryUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaEntryMutation
}

// Where appends a list predicates to the SchemaEntryUpdate builder.
func (seu *SchemaEntryUpdate) Where(ps ...predicate.SchemaEntry) *SchemaEntryUpdate {
	seu.mutation.Where(ps...)
	return seu
}

// SetHash sets the "hash" field.
func (seu *SchemaEntryUpdate) SetHash(s string) *SchemaEntryUpdate {
	seu.mutation.SetHash(s)
	return seu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (seu *SchemaEntryUpdate) SetNillableHash(s *string) *SchemaEntryUpdate {
	if s != nil {
		seu.SetHash(*s)
	}
	return seu
}

// SetCanonical sets the "canonical" field.
func (seu *SchemaEntryUpdate) SetCanonical(m map[string]interface{}) *SchemaEntryUpdate {
	seu.mutation.SetCanonical(m)
	return seu
}

// SetRuntimeOrigin sets the "runtime_origin" field.
func (seu *SchemaEntryUpdate) SetRuntimeOrigin(so schemaentry.RuntimeOrigin) *SchemaEntryUpdate {
	seu.mutation.SetRuntimeOrigin(so)
	return seu
}

// SetNillableRuntimeOrigin sets the "runtime_origin" field if the given value is not nil.
func (seu *SchemaEntryUpdate) SetNillableRuntimeOrigin(so *schemaentry.RuntimeOrigin) *SchemaEntryUpdate {
	if so != nil {
		seu.SetRuntimeOrigin(*so)
	}
	return seu
}

// Mutation returns the SchemaEntryMutation object of the builder.
func (seu *SchemaEntryUpdate) Mutation() *SchemaEntryMutation {
	return seu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (seu *SchemaEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, seu.sqlSave, seu.mutation, seu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seu *SchemaEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := seu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (seu *SchemaEntryUpdate) Exec(ctx context.Context) error {
	_, err := seu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seu *SchemaEntryUpdate) ExecX(ctx context.Context) {
	if err := seu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (seu *SchemaEntryUpdate) check() error {
	if v, ok := seu.mutation.Hash(); ok {
		if err := schemaentry.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "SchemaEntry.hash": %w`, err)}
		}
	}
	if v, ok := seu.mutation.RuntimeOrigin(); ok {
		if err := schemaentry.RuntimeOriginValidator(v); err != nil {
			return &ValidationError{Name: "runtime_origin", err: fmt.Errorf(`ent: validator failed for field "SchemaEntry.runtime_origin": %w`, err)}
		}
	}
	return nil
}

func (seu *SchemaEntryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := seu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(schemaentry.Table, schemaentry.Columns, sqlgraph.NewFieldSpec(schemaentry.FieldID, field.TypeInt))
	if ps := seu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seu.mutation.Hash(); ok {
		_spec.SetField(schemaentry.FieldHash, field.TypeString, value)
	}
	if value, ok := seu.mutation.Canonical(); ok {
		_spec.SetField(schemaentry.FieldCanonical, field.TypeJSON, value)
	}
	if value, ok := seu.mutation.RuntimeOrigin(); ok {
		_spec.SetField(schemaentry.FieldRuntimeOrigin, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, seu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemaentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	seu.mutation.done = true
	return n, nil
}

// SchemaEntryUpdateOne is the builder for updating a single SchemaEntry entity.
type SchemaEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaEntryMutation
}

// SetHash sets the "hash" field.
func (seuo *SchemaEntryUpdateOne) SetHash(s string) *SchemaEntryUpdateOne {
	seuo.mutation.SetHash(s)
	return seuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (seuo *SchemaEntryUpdateOne) SetNillableHash(s *string) *SchemaEntryUpdateOne {
	if s != nil {
		seuo.SetHash(*s)
	}
	return seuo
}

// SetCanonical sets the "canonical" field.
func (seuo *SchemaEntryUpdateOne) SetCanonical(m map[string]interface{}) *SchemaEntryUpdateOne {
	seuo.mutation.SetCanonical(m)
	return seuo
}

// SetRuntimeOrigin sets the "runtime_origin" field.
func (seuo *SchemaEntryUpdateOne) SetRuntimeOrigin(so schemaentry.RuntimeOrigin) *SchemaEntryUpdateOne {
	seuo.mutation.SetRuntimeOrigin(so)
	return seuo
}

// SetNillableRuntimeOrigin sets the "runtime_origin" field if the given value is not nil.
func (seuo *SchemaEntryUpdateOne) SetNillableRuntimeOrigin(so *schemaentry.RuntimeOrigin) *SchemaEntryUpdateOne {
	if so != nil {
		seuo.SetRuntimeOrigin(*so)
	}
	return seuo
}

// Mutation returns the SchemaEntryMutation object of the builder.
func (seuo *SchemaEntryUpdateOne) Mutation() *SchemaEntryMutation {
	return seuo.mutation
}

// Where appends a list predicates to the SchemaEntryUpdate builder.
func (seuo *SchemaEntryUpdateOne) Where(ps ...predicate.SchemaEntry) *SchemaEntryUpdateOne {
	seuo.mutation.Where(ps...)
	return seuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (seuo *SchemaEntryUpdateOne) Select(field string, fields ...string) *SchemaEntryUpdateOne {
	seuo.fields = append([]string{field}, fields...)
	return seuo
}

// Save executes the query and returns the updated SchemaEntry entity.
func (seuo *SchemaEntryUpdateOne) Save(ctx context.Context) (*SchemaEntry, error) {
	return withHooks(ctx, seuo.sqlSave, seuo.mutation, seuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seuo *SchemaEntryUpdateOne) SaveX(ctx context.Context) *SchemaEntry {
	node, err := seuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (seuo *SchemaEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := seuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seuo *SchemaEntryUpdateOne) ExecX(ctx context.Context) {
	if err := seuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (seuo *SchemaEntryUpdateOne) check() error {
	if v, ok := seuo.mutation.Hash(); ok {
		if err := schemaentry.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "SchemaEntry.hash": %w`, err)}
		}
	}
	if v, ok := seuo.mutation.RuntimeOrigin(); ok {
		if err := schemaentry.RuntimeOriginValidator(v); err != nil {
			return &ValidationError{Name: "runtime_origin", err: fmt.Errorf(`ent: validator failed for field "SchemaEntry.runtime_origin": %w`, err)}
		}
	}
	return nil
}

func (seuo *SchemaEntryUpdateOne) sqlSave(ctx context.Context) (_node *SchemaEntry, err error) {
	if err := seuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schemaentry.Table, schemaentry.Columns, sqlgraph.NewFieldSpec(schemaentry.FieldID, field.TypeInt))
	id, ok := seuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := seuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemaentry.FieldID)
		for _, f := range fields {
			if !schemaentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schemaentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := seuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seuo.mutation.Hash(); ok {
		_spec.SetField(schemaentry.FieldHash, field.TypeString, value)
	}
	if value, ok := seuo.mutation.Canonical(); ok {
		_spec.SetField(schemaentry.FieldCanonical, field.TypeJSON, value)
	}
	if value, ok := seuo.mutation.RuntimeOrigin(); ok {
		_spec.SetField(schemaentry.FieldRuntimeOrigin, field.TypeEnum, value)
	}
	_node = &SchemaEntry{config: seuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, seuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemaentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	seuo.mutation.done = true
	return _node, nil
}
