// Code generated by ent, DO NOT EDIT.

package llmproviderresolution

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the llmproviderresolution type in the database.
	Label = "llm_provider_resolution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConsumerAgentID holds the string denoting the consumer_agent_id field in the database.
	FieldConsumerAgentID = "consumer_agent_id"
	// FieldConsumerFunctionName holds the string denoting the consumer_function_name field in the database.
	FieldConsumerFunctionName = "consumer_function_name"
	// FieldRequiredCapability holds the string denoting the required_capability field in the database.
	FieldRequiredCapability = "required_capability"
	// FieldRequiredTags holds the string denoting the required_tags field in the database.
	FieldRequiredTags = "required_tags"
	// FieldRequiredVersion holds the string denoting the required_version field in the database.
	FieldRequiredVersion = "required_version"
	// FieldRequiredNamespace holds the string denoting the required_namespace field in the database.
	FieldRequiredNamespace = "required_namespace"
	// FieldProviderAgentID holds the string denoting the provider_agent_id field in the database.
	FieldProviderAgentID = "provider_agent_id"
	// FieldProviderFunctionName holds the string denoting the provider_function_name field in the database.
	FieldProviderFunctionName = "provider_function_name"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeConsumerAgent holds the string denoting the consumer_agent edge name in mutations.
	EdgeConsumerAgent = "consumer_agent"
	// EdgeProviderAgent holds the string denoting the provider_agent edge name in mutations.
	EdgeProviderAgent = "provider_agent"
	// AgentFieldID holds the string denoting the ID field of the Agent.
	AgentFieldID = "agent_id"
	// Table holds the table name of the llmproviderresolution in the database.
	Table = "llm_provider_resolutions"
	// ConsumerAgentTable is the table that holds the consumer_agent relation/edge.
	ConsumerAgentTable = "llm_provider_resolutions"
	// ConsumerAgentInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	ConsumerAgentInverseTable = "agents"
	// ConsumerAgentColumn is the table column denoting the consumer_agent relation/edge.
	ConsumerAgentColumn = "consumer_agent_id"
	// ProviderAgentTable is the table that holds the provider_agent relation/edge.
	ProviderAgentTable = "llm_provider_resolutions"
	// ProviderAgentInverseTable is the table name for the Agent entity.
	// It exists in this package in order to avoid circular dependency with the "agent" package.
	ProviderAgentInverseTable = "agents"
	// ProviderAgentColumn is the table column denoting the provider_agent relation/edge.
	ProviderAgentColumn = "provider_agent_id"
)

// Columns holds all SQL columns for llmproviderresolution fields.
var Columns = []string{
	FieldID,
	FieldConsumerAgentID,
	FieldConsumerFunctionName,
	FieldRequiredCapability,
	FieldRequiredTags,
	FieldRequiredVersion,
	FieldRequiredNamespace,
	FieldProviderAgentID,
	FieldProviderFunctionName,
	FieldEndpoint,
	FieldStatus,
	FieldResolvedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequiredNamespace holds the default value on creation for the "required_namespace" field.
	DefaultRequiredNamespace string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnresolved is the default value of the Status enum.
const DefaultStatus = StatusUnresolved

// Status values.
const (
	StatusAvailable   Status = "available"
	StatusUnavailable Status = "unavailable"
	StatusUnresolved  Status = "unresolved"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusUnavailable, StatusUnresolved:
		return nil
	default:
		return fmt.Errorf("llmproviderresolution: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the LLMProviderResolution queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConsumerAgentID orders the results by the consumer_agent_id field.
func ByConsumerAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerAgentID, opts...).ToFunc()
}

// ByConsumerFunctionName orders the results by the consumer_function_name field.
func ByConsumerFunctionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerFunctionName, opts...).ToFunc()
}

// ByRequiredCapability orders the results by the required_capability field.
func ByRequiredCapability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredCapability, opts...).ToFunc()
}

// ByRequiredVersion orders the results by the required_version field.
func ByRequiredVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredVersion, opts...).ToFunc()
}

// ByRequiredNamespace orders the results by the required_namespace field.
func ByRequiredNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiredNamespace, opts...).ToFunc()
}

// ByProviderAgentID orders the results by the provider_agent_id field.
func ByProviderAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderAgentID, opts...).ToFunc()
}

// ByProviderFunctionName orders the results by the provider_function_name field.
func ByProviderFunctionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderFunctionName, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByConsumerAgentField orders the results by consumer_agent field.
func ByConsumerAgentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsumerAgentStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderAgentField orders the results by provider_agent field.
func ByProviderAgentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderAgentStep(), sql.OrderByField(field, opts...))
	}
}
func newConsumerAgentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsumerAgentInverseTable, AgentFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConsumerAgentTable, ConsumerAgentColumn),
	)
}
func newProviderAgentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderAgentInverseTable, AgentFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProviderAgentTable, ProviderAgentColumn),
	)
}
