// Code generated by ent, DO NOT EDIT.

package llmproviderresolution

import (
	"mcp-mesh/src/core/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldID, id))
}

// ConsumerAgentID applies equality check predicate on the "consumer_agent_id" field. It's identical to ConsumerAgentIDEQ.
func ConsumerAgentID(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldConsumerAgentID, v))
}

// ConsumerFunctionName applies equality check predicate on the "consumer_function_name" field. It's identical to ConsumerFunctionNameEQ.
func ConsumerFunctionName(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldConsumerFunctionName, v))
}

// RequiredCapability applies equality check predicate on the "required_capability" field. It's identical to RequiredCapabilityEQ.
func RequiredCapability(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredCapability, v))
}

// RequiredVersion applies equality check predicate on the "required_version" field. It's identical to RequiredVersionEQ.
func RequiredVersion(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredVersion, v))
}

// RequiredNamespace applies equality check predicate on the "required_namespace" field. It's identical to RequiredNamespaceEQ.
func RequiredNamespace(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredNamespace, v))
}

// ProviderAgentID applies equality check predicate on the "provider_agent_id" field. It's identical to ProviderAgentIDEQ.
func ProviderAgentID(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldProviderAgentID, v))
}

// ProviderFunctionName applies equality check predicate on the "provider_function_name" field. It's identical to ProviderFunctionNameEQ.
func ProviderFunctionName(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldProviderFunctionName, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldEndpoint, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldResolvedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConsumerAgentIDEQ applies the EQ predicate on the "consumer_agent_id" field.
func ConsumerAgentIDEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldConsumerAgentID, v))
}

// ConsumerAgentIDNEQ applies the NEQ predicate on the "consumer_agent_id" field.
func ConsumerAgentIDNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldConsumerAgentID, v))
}

// ConsumerAgentIDIn applies the In predicate on the "consumer_agent_id" field.
func ConsumerAgentIDIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldConsumerAgentID, vs...))
}

// ConsumerAgentIDNotIn applies the NotIn predicate on the "consumer_agent_id" field.
func ConsumerAgentIDNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldConsumerAgentID, vs...))
}

// ConsumerAgentIDGT applies the GT predicate on the "consumer_agent_id" field.
func ConsumerAgentIDGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldConsumerAgentID, v))
}

// ConsumerAgentIDGTE applies the GTE predicate on the "consumer_agent_id" field.
func ConsumerAgentIDGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldConsumerAgentID, v))
}

// ConsumerAgentIDLT applies the LT predicate on the "consumer_agent_id" field.
func ConsumerAgentIDLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldConsumerAgentID, v))
}

// ConsumerAgentIDLTE applies the LTE predicate on the "consumer_agent_id" field.
func ConsumerAgentIDLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldConsumerAgentID, v))
}

// ConsumerAgentIDContains applies the Contains predicate on the "consumer_agent_id" field.
func ConsumerAgentIDContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldConsumerAgentID, v))
}

// ConsumerAgentIDHasPrefix applies the HasPrefix predicate on the "consumer_agent_id" field.
func ConsumerAgentIDHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldConsumerAgentID, v))
}

// ConsumerAgentIDHasSuffix applies the HasSuffix predicate on the "consumer_agent_id" field.
func ConsumerAgentIDHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldConsumerAgentID, v))
}

// ConsumerAgentIDEqualFold applies the EqualFold predicate on the "consumer_agent_id" field.
func ConsumerAgentIDEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldConsumerAgentID, v))
}

// ConsumerAgentIDContainsFold applies the ContainsFold predicate on the "consumer_agent_id" field.
func ConsumerAgentIDContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldConsumerAgentID, v))
}

// ConsumerFunctionNameEQ applies the EQ predicate on the "consumer_function_name" field.
func ConsumerFunctionNameEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameNEQ applies the NEQ predicate on the "consumer_function_name" field.
func ConsumerFunctionNameNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameIn applies the In predicate on the "consumer_function_name" field.
func ConsumerFunctionNameIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldConsumerFunctionName, vs...))
}

// ConsumerFunctionNameNotIn applies the NotIn predicate on the "consumer_function_name" field.
func ConsumerFunctionNameNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldConsumerFunctionName, vs...))
}

// ConsumerFunctionNameGT applies the GT predicate on the "consumer_function_name" field.
func ConsumerFunctionNameGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameGTE applies the GTE predicate on the "consumer_function_name" field.
func ConsumerFunctionNameGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameLT applies the LT predicate on the "consumer_function_name" field.
func ConsumerFunctionNameLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameLTE applies the LTE predicate on the "consumer_function_name" field.
func ConsumerFunctionNameLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameContains applies the Contains predicate on the "consumer_function_name" field.
func ConsumerFunctionNameContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameHasPrefix applies the HasPrefix predicate on the "consumer_function_name" field.
func ConsumerFunctionNameHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameHasSuffix applies the HasSuffix predicate on the "consumer_function_name" field.
func ConsumerFunctionNameHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameEqualFold applies the EqualFold predicate on the "consumer_function_name" field.
func ConsumerFunctionNameEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameContainsFold applies the ContainsFold predicate on the "consumer_function_name" field.
func ConsumerFunctionNameContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldConsumerFunctionName, v))
}

// RequiredCapabilityEQ applies the EQ predicate on the "required_capability" field.
func RequiredCapabilityEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredCapability, v))
}

// RequiredCapabilityNEQ applies the NEQ predicate on the "required_capability" field.
func RequiredCapabilityNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldRequiredCapability, v))
}

// RequiredCapabilityIn applies the In predicate on the "required_capability" field.
func RequiredCapabilityIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldRequiredCapability, vs...))
}

// RequiredCapabilityNotIn applies the NotIn predicate on the "required_capability" field.
func RequiredCapabilityNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldRequiredCapability, vs...))
}

// RequiredCapabilityGT applies the GT predicate on the "required_capability" field.
func RequiredCapabilityGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldRequiredCapability, v))
}

// RequiredCapabilityGTE applies the GTE predicate on the "required_capability" field.
func RequiredCapabilityGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldRequiredCapability, v))
}

// RequiredCapabilityLT applies the LT predicate on the "required_capability" field.
func RequiredCapabilityLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldRequiredCapability, v))
}

// RequiredCapabilityLTE applies the LTE predicate on the "required_capability" field.
func RequiredCapabilityLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldRequiredCapability, v))
}

// RequiredCapabilityContains applies the Contains predicate on the "required_capability" field.
func RequiredCapabilityContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldRequiredCapability, v))
}

// RequiredCapabilityHasPrefix applies the HasPrefix predicate on the "required_capability" field.
func RequiredCapabilityHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldRequiredCapability, v))
}

// RequiredCapabilityHasSuffix applies the HasSuffix predicate on the "required_capability" field.
func RequiredCapabilityHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldRequiredCapability, v))
}

// RequiredCapabilityEqualFold applies the EqualFold predicate on the "required_capability" field.
func RequiredCapabilityEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldRequiredCapability, v))
}

// RequiredCapabilityContainsFold applies the ContainsFold predicate on the "required_capability" field.
func RequiredCapabilityContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldRequiredCapability, v))
}

// RequiredTagsIsNil applies the IsNil predicate on the "required_tags" field.
func RequiredTagsIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldRequiredTags))
}

// RequiredTagsNotNil applies the NotNil predicate on the "required_tags" field.
func RequiredTagsNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldRequiredTags))
}

// RequiredVersionEQ applies the EQ predicate on the "required_version" field.
func RequiredVersionEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredVersion, v))
}

// RequiredVersionNEQ applies the NEQ predicate on the "required_version" field.
func RequiredVersionNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldRequiredVersion, v))
}

// RequiredVersionIn applies the In predicate on the "required_version" field.
func RequiredVersionIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldRequiredVersion, vs...))
}

// RequiredVersionNotIn applies the NotIn predicate on the "required_version" field.
func RequiredVersionNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldRequiredVersion, vs...))
}

// RequiredVersionGT applies the GT predicate on the "required_version" field.
func RequiredVersionGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldRequiredVersion, v))
}

// RequiredVersionGTE applies the GTE predicate on the "required_version" field.
func RequiredVersionGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldRequiredVersion, v))
}

// RequiredVersionLT applies the LT predicate on the "required_version" field.
func RequiredVersionLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldRequiredVersion, v))
}

// RequiredVersionLTE applies the LTE predicate on the "required_version" field.
func RequiredVersionLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldRequiredVersion, v))
}

// RequiredVersionContains applies the Contains predicate on the "required_version" field.
func RequiredVersionContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldRequiredVersion, v))
}

// RequiredVersionHasPrefix applies the HasPrefix predicate on the "required_version" field.
func RequiredVersionHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldRequiredVersion, v))
}

// RequiredVersionHasSuffix applies the HasSuffix predicate on the "required_version" field.
func RequiredVersionHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldRequiredVersion, v))
}

// RequiredVersionIsNil applies the IsNil predicate on the "required_version" field.
func RequiredVersionIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldRequiredVersion))
}

// RequiredVersionNotNil applies the NotNil predicate on the "required_version" field.
func RequiredVersionNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldRequiredVersion))
}

// RequiredVersionEqualFold applies the EqualFold predicate on the "required_version" field.
func RequiredVersionEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldRequiredVersion, v))
}

// RequiredVersionContainsFold applies the ContainsFold predicate on the "required_version" field.
func RequiredVersionContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldRequiredVersion, v))
}

// RequiredNamespaceEQ applies the EQ predicate on the "required_namespace" field.
func RequiredNamespaceEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldRequiredNamespace, v))
}

// RequiredNamespaceNEQ applies the NEQ predicate on the "required_namespace" field.
func RequiredNamespaceNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldRequiredNamespace, v))
}

// RequiredNamespaceIn applies the In predicate on the "required_namespace" field.
func RequiredNamespaceIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldRequiredNamespace, vs...))
}

// RequiredNamespaceNotIn applies the NotIn predicate on the "required_namespace" field.
func RequiredNamespaceNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldRequiredNamespace, vs...))
}

// RequiredNamespaceGT applies the GT predicate on the "required_namespace" field.
func RequiredNamespaceGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldRequiredNamespace, v))
}

// RequiredNamespaceGTE applies the GTE predicate on the "required_namespace" field.
func RequiredNamespaceGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldRequiredNamespace, v))
}

// RequiredNamespaceLT applies the LT predicate on the "required_namespace" field.
func RequiredNamespaceLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldRequiredNamespace, v))
}

// RequiredNamespaceLTE applies the LTE predicate on the "required_namespace" field.
func RequiredNamespaceLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldRequiredNamespace, v))
}

// RequiredNamespaceContains applies the Contains predicate on the "required_namespace" field.
func RequiredNamespaceContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldRequiredNamespace, v))
}

// RequiredNamespaceHasPrefix applies the HasPrefix predicate on the "required_namespace" field.
func RequiredNamespaceHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldRequiredNamespace, v))
}

// RequiredNamespaceHasSuffix applies the HasSuffix predicate on the "required_namespace" field.
func RequiredNamespaceHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldRequiredNamespace, v))
}

// RequiredNamespaceEqualFold applies the EqualFold predicate on the "required_namespace" field.
func RequiredNamespaceEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldRequiredNamespace, v))
}

// RequiredNamespaceContainsFold applies the ContainsFold predicate on the "required_namespace" field.
func RequiredNamespaceContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldRequiredNamespace, v))
}

// ProviderAgentIDEQ applies the EQ predicate on the "provider_agent_id" field.
func ProviderAgentIDEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldProviderAgentID, v))
}

// ProviderAgentIDNEQ applies the NEQ predicate on the "provider_agent_id" field.
func ProviderAgentIDNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldProviderAgentID, v))
}

// ProviderAgentIDIn applies the In predicate on the "provider_agent_id" field.
func ProviderAgentIDIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldProviderAgentID, vs...))
}

// ProviderAgentIDNotIn applies the NotIn predicate on the "provider_agent_id" field.
func ProviderAgentIDNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldProviderAgentID, vs...))
}

// ProviderAgentIDGT applies the GT predicate on the "provider_agent_id" field.
func ProviderAgentIDGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldProviderAgentID, v))
}

// ProviderAgentIDGTE applies the GTE predicate on the "provider_agent_id" field.
func ProviderAgentIDGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldProviderAgentID, v))
}

// ProviderAgentIDLT applies the LT predicate on the "provider_agent_id" field.
func ProviderAgentIDLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldProviderAgentID, v))
}

// ProviderAgentIDLTE applies the LTE predicate on the "provider_agent_id" field.
func ProviderAgentIDLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldProviderAgentID, v))
}

// ProviderAgentIDContains applies the Contains predicate on the "provider_agent_id" field.
func ProviderAgentIDContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldProviderAgentID, v))
}

// ProviderAgentIDHasPrefix applies the HasPrefix predicate on the "provider_agent_id" field.
func ProviderAgentIDHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldProviderAgentID, v))
}

// ProviderAgentIDHasSuffix applies the HasSuffix predicate on the "provider_agent_id" field.
func ProviderAgentIDHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldProviderAgentID, v))
}

// ProviderAgentIDIsNil applies the IsNil predicate on the "provider_agent_id" field.
func ProviderAgentIDIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldProviderAgentID))
}

// ProviderAgentIDNotNil applies the NotNil predicate on the "provider_agent_id" field.
func ProviderAgentIDNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldProviderAgentID))
}

// ProviderAgentIDEqualFold applies the EqualFold predicate on the "provider_agent_id" field.
func ProviderAgentIDEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldProviderAgentID, v))
}

// ProviderAgentIDContainsFold applies the ContainsFold predicate on the "provider_agent_id" field.
func ProviderAgentIDContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldProviderAgentID, v))
}

// ProviderFunctionNameEQ applies the EQ predicate on the "provider_function_name" field.
func ProviderFunctionNameEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldProviderFunctionName, v))
}

// ProviderFunctionNameNEQ applies the NEQ predicate on the "provider_function_name" field.
func ProviderFunctionNameNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldProviderFunctionName, v))
}

// ProviderFunctionNameIn applies the In predicate on the "provider_function_name" field.
func ProviderFunctionNameIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldProviderFunctionName, vs...))
}

// ProviderFunctionNameNotIn applies the NotIn predicate on the "provider_function_name" field.
func ProviderFunctionNameNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldProviderFunctionName, vs...))
}

// ProviderFunctionNameGT applies the GT predicate on the "provider_function_name" field.
func ProviderFunctionNameGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldProviderFunctionName, v))
}

// ProviderFunctionNameGTE applies the GTE predicate on the "provider_function_name" field.
func ProviderFunctionNameGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldProviderFunctionName, v))
}

// ProviderFunctionNameLT applies the LT predicate on the "provider_function_name" field.
func ProviderFunctionNameLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldProviderFunctionName, v))
}

// ProviderFunctionNameLTE applies the LTE predicate on the "provider_function_name" field.
func ProviderFunctionNameLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldProviderFunctionName, v))
}

// ProviderFunctionNameContains applies the Contains predicate on the "provider_function_name" field.
func ProviderFunctionNameContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldProviderFunctionName, v))
}

// ProviderFunctionNameHasPrefix applies the HasPrefix predicate on the "provider_function_name" field.
func ProviderFunctionNameHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldProviderFunctionName, v))
}

// ProviderFunctionNameHasSuffix applies the HasSuffix predicate on the "provider_function_name" field.
func ProviderFunctionNameHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldProviderFunctionName, v))
}

// ProviderFunctionNameIsNil applies the IsNil predicate on the "provider_function_name" field.
func ProviderFunctionNameIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldProviderFunctionName))
}

// ProviderFunctionNameNotNil applies the NotNil predicate on the "provider_function_name" field.
func ProviderFunctionNameNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldProviderFunctionName))
}

// ProviderFunctionNameEqualFold applies the EqualFold predicate on the "provider_function_name" field.
func ProviderFunctionNameEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldProviderFunctionName, v))
}

// ProviderFunctionNameContainsFold applies the ContainsFold predicate on the "provider_function_name" field.
func ProviderFunctionNameContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldProviderFunctionName, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointIsNil applies the IsNil predicate on the "endpoint" field.
func EndpointIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldEndpoint))
}

// EndpointNotNil applies the NotNil predicate on the "endpoint" field.
func EndpointNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldEndpoint))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldContainsFold(FieldEndpoint, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldStatus, vs...))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotNull(FieldResolvedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasConsumerAgent applies the HasEdge predicate on the "consumer_agent" edge.
func HasConsumerAgent() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConsumerAgentTable, ConsumerAgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConsumerAgentWith applies the HasEdge predicate on the "consumer_agent" edge with a given conditions (other predicates).
func HasConsumerAgentWith(preds ...predicate.Agent) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(func(s *sql.Selector) {
		step := newConsumerAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderAgent applies the HasEdge predicate on the "provider_agent" edge.
func HasProviderAgent() predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProviderAgentTable, ProviderAgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderAgentWith applies the HasEdge predicate on the "provider_agent" edge with a given conditions (other predicates).
func HasProviderAgentWith(preds ...predicate.Agent) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(func(s *sql.Selector) {
		step := newProviderAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LLMProviderResolution) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LLMProviderResolution) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LLMProviderResolution) predicate.LLMProviderResolution {
	return predicate.LLMProviderResolution(sql.NotPredicates(p))
}
