// BUILD-TIME ONLY — the copy the docs page serves, rendered from script.ts.
//
// WHAT THIS IS FOR. The section is ~2205vh of pinned scroll carrying fourteen
// beats and a six-phase epilogue, and until this existed none of that prose was
// in the served document: the whole shell was a JSON string inside the bundle,
// injected client-side. A crawler, a reader with JavaScript off and
// find-in-page all got a single hand-written placeholder. This emits the real
// thing, from the same `script.ts` the animation reads, so the two cannot drift
// and nobody has to remember to update a second copy.
//
// The output is committed (see emit.tsx for why) and included by docs/index.md
// through pymdownx.snippets. The beat blocks are the SAME markup <Stage>
// renders, because they are the same component — the driver moves these nodes
// into the animation rather than rendering its own set.
import { renderToStaticMarkup } from "react-dom/server";

import { BEATS, REVEAL } from "./script";
import {
  BeatBlock, RevealTitle, RevealSub, PhaseCopy, CtaCopy,
} from "./stage";

/**
 * The epilogue as prose.
 *
 * Not adopted by the driver — the prerendered shell renders its own headline,
 * phase grid and call to action, positioned for the panel. This is the reading
 * of them, for the document that is served before (or without) the bundle.
 *
 * ONLY THE WRAPPERS ARE HERE. The words, their elements and their type come
 * from the same components <Stage> sets them with, for exactly the reason the
 * beat blocks do: this file used to hand-copy the whole epilogue out of
 * stage.tsx, and by the time anyone compared them the call to action had
 * already been rendered with the wrong inline style — its code spans a shade
 * off from the panel's, in committed output, with nothing able to say so. The
 * arrangement is the one thing a linear column and a pinned panel cannot share,
 * so the arrangement is all that is written twice.
 */
// Rendered a piece at a time so each one lands on its own line — see
// renderPartial. A single render of the whole epilogue would emit ~1.4 kB of
// prose as one line, and every wording change would show up as that whole line.
const revealParts = (): string[] => [
  renderToStaticMarkup(<RevealTitle />),
  renderToStaticMarkup(<RevealSub />),
  ...REVEAL.phases.map((p) =>
    renderToStaticMarkup(
      <div className="mesh-scroll-phase">
        <PhaseCopy phase={p} />
      </div>
    )
  ),
  renderToStaticMarkup(
    <div className="mesh-scroll-cta">
      <CtaCopy />
    </div>
  ),
];

/**
 * Authored line breaks, made to survive the docs build.
 *
 * Three strings in script.ts carry a `\n` and are set with `white-space:
 * pre-line`, because where they break is a composition decision — B5's title
 * splits after "asked" so the repetition the line is built on is not buried by
 * the natural wrap, and two sub-lines break to keep a "·" off the end of a
 * line. Those newlines used to live in a JSON string inside the bundle, which
 * nothing touched. In the served document they are HTML text, and mkdocs-minify
 * runs with minify_html: it collapses the newline to a space and the break is
 * silently gone.
 *
 * The numeric character reference is not collapsed, and the parser turns it
 * back into the same newline — so what the driver adopts is character-identical
 * to what <Stage> renders, which is what layer 4 in emit.tsx checks.
 *
 * Caught by a pixel diff of the built page against the previous build, not by
 * any assertion here: every count and every guard passed with the break gone.
 */
const keepBreaks = (html: string) => html.split("\n").join("&#10;");

const BANNER =
  "<!-- GENERATED by src/ui/demo/partial.tsx from src/ui/demo/script.ts. " +
  "Do not edit: `make docs-scroll-prerender` rewrites it, and CI fails on any " +
  "difference. The wording of record is src/ui/demo/copy.md. -->";

/**
 * One block per beat, as the driver will adopt them. No hidden state on any of
 * them — that is written per frame from the opacities, by whichever renderer is
 * animating, and nothing is animating in the served document.
 */
export const beatBlocks = (): string[] =>
  BEATS.map((b, i) => renderToStaticMarkup(<BeatBlock beat={b} index={i} />));

/**
 * The whole partial. One block per line — this is product prose and it has to
 * be readable in a pull request diff, where a re-rendered single line would
 * not be.
 */
export function renderPartial(): string {
  return [
    BANNER,
    '<div class="mesh-scroll-copy">',
    ...beatBlocks().map(keepBreaks),
    '<div class="mesh-scroll-reveal">',
    ...revealParts().map(keepBreaks),
    "</div>",
    "</div>",
    "",
    // The joins are what put one block per line; keepBreaks runs on each part
    // BEFORE that, so the file's own newlines are structure and every newline
    // inside a block is copy.
  ].join("\n");
}
