{{- if include "mcp-mesh-ui.secretEnabled" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-mesh-ui.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-mesh-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not (include "mcp-mesh-ui.databaseExistingSecret" .) }}
  DATABASE_URL: {{ include "mcp-mesh-ui.databaseURL" . | quote }}
  {{- end }}
  {{- if not (include "mcp-mesh-ui.redisExistingSecret" .) }}
  REDIS_URL: {{ include "mcp-mesh-ui.redisURL" . | quote }}
  {{- end }}
{{- end }}
