// Code generated by ent, DO NOT EDIT.

package dependencyresolution

import (
	"mcp-mesh/src/core/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldID, id))
}

// ConsumerAgentID applies equality check predicate on the "consumer_agent_id" field. It's identical to ConsumerAgentIDEQ.
func ConsumerAgentID(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldConsumerAgentID, v))
}

// ConsumerFunctionName applies equality check predicate on the "consumer_function_name" field. It's identical to ConsumerFunctionNameEQ.
func ConsumerFunctionName(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldConsumerFunctionName, v))
}

// CapabilityRequired applies equality check predicate on the "capability_required" field. It's identical to CapabilityRequiredEQ.
func CapabilityRequired(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldCapabilityRequired, v))
}

// VersionRequired applies equality check predicate on the "version_required" field. It's identical to VersionRequiredEQ.
func VersionRequired(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldVersionRequired, v))
}

// NamespaceRequired applies equality check predicate on the "namespace_required" field. It's identical to NamespaceRequiredEQ.
func NamespaceRequired(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldNamespaceRequired, v))
}

// ProviderAgentID applies equality check predicate on the "provider_agent_id" field. It's identical to ProviderAgentIDEQ.
func ProviderAgentID(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldProviderAgentID, v))
}

// ProviderFunctionName applies equality check predicate on the "provider_function_name" field. It's identical to ProviderFunctionNameEQ.
func ProviderFunctionName(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldProviderFunctionName, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldEndpoint, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldResolvedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldUpdatedAt, v))
}

// ConsumerAgentIDEQ applies the EQ predicate on the "consumer_agent_id" field.
func ConsumerAgentIDEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldConsumerAgentID, v))
}

// ConsumerAgentIDNEQ applies the NEQ predicate on the "consumer_agent_id" field.
func ConsumerAgentIDNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldConsumerAgentID, v))
}

// ConsumerAgentIDIn applies the In predicate on the "consumer_agent_id" field.
func ConsumerAgentIDIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldConsumerAgentID, vs...))
}

// ConsumerAgentIDNotIn applies the NotIn predicate on the "consumer_agent_id" field.
func ConsumerAgentIDNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldConsumerAgentID, vs...))
}

// ConsumerAgentIDGT applies the GT predicate on the "consumer_agent_id" field.
func ConsumerAgentIDGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldConsumerAgentID, v))
}

// ConsumerAgentIDGTE applies the GTE predicate on the "consumer_agent_id" field.
func ConsumerAgentIDGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldConsumerAgentID, v))
}

// ConsumerAgentIDLT applies the LT predicate on the "consumer_agent_id" field.
func ConsumerAgentIDLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldConsumerAgentID, v))
}

// ConsumerAgentIDLTE applies the LTE predicate on the "consumer_agent_id" field.
func ConsumerAgentIDLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldConsumerAgentID, v))
}

// ConsumerAgentIDContains applies the Contains predicate on the "consumer_agent_id" field.
func ConsumerAgentIDContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldConsumerAgentID, v))
}

// ConsumerAgentIDHasPrefix applies the HasPrefix predicate on the "consumer_agent_id" field.
func ConsumerAgentIDHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldConsumerAgentID, v))
}

// ConsumerAgentIDHasSuffix applies the HasSuffix predicate on the "consumer_agent_id" field.
func ConsumerAgentIDHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldConsumerAgentID, v))
}

// ConsumerAgentIDEqualFold applies the EqualFold predicate on the "consumer_agent_id" field.
func ConsumerAgentIDEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldConsumerAgentID, v))
}

// ConsumerAgentIDContainsFold applies the ContainsFold predicate on the "consumer_agent_id" field.
func ConsumerAgentIDContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldConsumerAgentID, v))
}

// ConsumerFunctionNameEQ applies the EQ predicate on the "consumer_function_name" field.
func ConsumerFunctionNameEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameNEQ applies the NEQ predicate on the "consumer_function_name" field.
func ConsumerFunctionNameNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameIn applies the In predicate on the "consumer_function_name" field.
func ConsumerFunctionNameIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldConsumerFunctionName, vs...))
}

// ConsumerFunctionNameNotIn applies the NotIn predicate on the "consumer_function_name" field.
func ConsumerFunctionNameNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldConsumerFunctionName, vs...))
}

// ConsumerFunctionNameGT applies the GT predicate on the "consumer_function_name" field.
func ConsumerFunctionNameGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameGTE applies the GTE predicate on the "consumer_function_name" field.
func ConsumerFunctionNameGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameLT applies the LT predicate on the "consumer_function_name" field.
func ConsumerFunctionNameLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameLTE applies the LTE predicate on the "consumer_function_name" field.
func ConsumerFunctionNameLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameContains applies the Contains predicate on the "consumer_function_name" field.
func ConsumerFunctionNameContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameHasPrefix applies the HasPrefix predicate on the "consumer_function_name" field.
func ConsumerFunctionNameHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameHasSuffix applies the HasSuffix predicate on the "consumer_function_name" field.
func ConsumerFunctionNameHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameEqualFold applies the EqualFold predicate on the "consumer_function_name" field.
func ConsumerFunctionNameEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldConsumerFunctionName, v))
}

// ConsumerFunctionNameContainsFold applies the ContainsFold predicate on the "consumer_function_name" field.
func ConsumerFunctionNameContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldConsumerFunctionName, v))
}

// CapabilityRequiredEQ applies the EQ predicate on the "capability_required" field.
func CapabilityRequiredEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldCapabilityRequired, v))
}

// CapabilityRequiredNEQ applies the NEQ predicate on the "capability_required" field.
func CapabilityRequiredNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldCapabilityRequired, v))
}

// CapabilityRequiredIn applies the In predicate on the "capability_required" field.
func CapabilityRequiredIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldCapabilityRequired, vs...))
}

// CapabilityRequiredNotIn applies the NotIn predicate on the "capability_required" field.
func CapabilityRequiredNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldCapabilityRequired, vs...))
}

// CapabilityRequiredGT applies the GT predicate on the "capability_required" field.
func CapabilityRequiredGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldCapabilityRequired, v))
}

// CapabilityRequiredGTE applies the GTE predicate on the "capability_required" field.
func CapabilityRequiredGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldCapabilityRequired, v))
}

// CapabilityRequiredLT applies the LT predicate on the "capability_required" field.
func CapabilityRequiredLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldCapabilityRequired, v))
}

// CapabilityRequiredLTE applies the LTE predicate on the "capability_required" field.
func CapabilityRequiredLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldCapabilityRequired, v))
}

// CapabilityRequiredContains applies the Contains predicate on the "capability_required" field.
func CapabilityRequiredContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldCapabilityRequired, v))
}

// CapabilityRequiredHasPrefix applies the HasPrefix predicate on the "capability_required" field.
func CapabilityRequiredHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldCapabilityRequired, v))
}

// CapabilityRequiredHasSuffix applies the HasSuffix predicate on the "capability_required" field.
func CapabilityRequiredHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldCapabilityRequired, v))
}

// CapabilityRequiredEqualFold applies the EqualFold predicate on the "capability_required" field.
func CapabilityRequiredEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldCapabilityRequired, v))
}

// CapabilityRequiredContainsFold applies the ContainsFold predicate on the "capability_required" field.
func CapabilityRequiredContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldCapabilityRequired, v))
}

// TagsRequiredIsNil applies the IsNil predicate on the "tags_required" field.
func TagsRequiredIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldTagsRequired))
}

// TagsRequiredNotNil applies the NotNil predicate on the "tags_required" field.
func TagsRequiredNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldTagsRequired))
}

// VersionRequiredEQ applies the EQ predicate on the "version_required" field.
func VersionRequiredEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldVersionRequired, v))
}

// VersionRequiredNEQ applies the NEQ predicate on the "version_required" field.
func VersionRequiredNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldVersionRequired, v))
}

// VersionRequiredIn applies the In predicate on the "version_required" field.
func VersionRequiredIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldVersionRequired, vs...))
}

// VersionRequiredNotIn applies the NotIn predicate on the "version_required" field.
func VersionRequiredNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldVersionRequired, vs...))
}

// VersionRequiredGT applies the GT predicate on the "version_required" field.
func VersionRequiredGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldVersionRequired, v))
}

// VersionRequiredGTE applies the GTE predicate on the "version_required" field.
func VersionRequiredGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldVersionRequired, v))
}

// VersionRequiredLT applies the LT predicate on the "version_required" field.
func VersionRequiredLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldVersionRequired, v))
}

// VersionRequiredLTE applies the LTE predicate on the "version_required" field.
func VersionRequiredLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldVersionRequired, v))
}

// VersionRequiredContains applies the Contains predicate on the "version_required" field.
func VersionRequiredContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldVersionRequired, v))
}

// VersionRequiredHasPrefix applies the HasPrefix predicate on the "version_required" field.
func VersionRequiredHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldVersionRequired, v))
}

// VersionRequiredHasSuffix applies the HasSuffix predicate on the "version_required" field.
func VersionRequiredHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldVersionRequired, v))
}

// VersionRequiredIsNil applies the IsNil predicate on the "version_required" field.
func VersionRequiredIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldVersionRequired))
}

// VersionRequiredNotNil applies the NotNil predicate on the "version_required" field.
func VersionRequiredNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldVersionRequired))
}

// VersionRequiredEqualFold applies the EqualFold predicate on the "version_required" field.
func VersionRequiredEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldVersionRequired, v))
}

// VersionRequiredContainsFold applies the ContainsFold predicate on the "version_required" field.
func VersionRequiredContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldVersionRequired, v))
}

// NamespaceRequiredEQ applies the EQ predicate on the "namespace_required" field.
func NamespaceRequiredEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldNamespaceRequired, v))
}

// NamespaceRequiredNEQ applies the NEQ predicate on the "namespace_required" field.
func NamespaceRequiredNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldNamespaceRequired, v))
}

// NamespaceRequiredIn applies the In predicate on the "namespace_required" field.
func NamespaceRequiredIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldNamespaceRequired, vs...))
}

// NamespaceRequiredNotIn applies the NotIn predicate on the "namespace_required" field.
func NamespaceRequiredNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldNamespaceRequired, vs...))
}

// NamespaceRequiredGT applies the GT predicate on the "namespace_required" field.
func NamespaceRequiredGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldNamespaceRequired, v))
}

// NamespaceRequiredGTE applies the GTE predicate on the "namespace_required" field.
func NamespaceRequiredGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldNamespaceRequired, v))
}

// NamespaceRequiredLT applies the LT predicate on the "namespace_required" field.
func NamespaceRequiredLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldNamespaceRequired, v))
}

// NamespaceRequiredLTE applies the LTE predicate on the "namespace_required" field.
func NamespaceRequiredLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldNamespaceRequired, v))
}

// NamespaceRequiredContains applies the Contains predicate on the "namespace_required" field.
func NamespaceRequiredContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldNamespaceRequired, v))
}

// NamespaceRequiredHasPrefix applies the HasPrefix predicate on the "namespace_required" field.
func NamespaceRequiredHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldNamespaceRequired, v))
}

// NamespaceRequiredHasSuffix applies the HasSuffix predicate on the "namespace_required" field.
func NamespaceRequiredHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldNamespaceRequired, v))
}

// NamespaceRequiredEqualFold applies the EqualFold predicate on the "namespace_required" field.
func NamespaceRequiredEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldNamespaceRequired, v))
}

// NamespaceRequiredContainsFold applies the ContainsFold predicate on the "namespace_required" field.
func NamespaceRequiredContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldNamespaceRequired, v))
}

// ProviderAgentIDEQ applies the EQ predicate on the "provider_agent_id" field.
func ProviderAgentIDEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldProviderAgentID, v))
}

// ProviderAgentIDNEQ applies the NEQ predicate on the "provider_agent_id" field.
func ProviderAgentIDNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldProviderAgentID, v))
}

// ProviderAgentIDIn applies the In predicate on the "provider_agent_id" field.
func ProviderAgentIDIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldProviderAgentID, vs...))
}

// ProviderAgentIDNotIn applies the NotIn predicate on the "provider_agent_id" field.
func ProviderAgentIDNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldProviderAgentID, vs...))
}

// ProviderAgentIDGT applies the GT predicate on the "provider_agent_id" field.
func ProviderAgentIDGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldProviderAgentID, v))
}

// ProviderAgentIDGTE applies the GTE predicate on the "provider_agent_id" field.
func ProviderAgentIDGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldProviderAgentID, v))
}

// ProviderAgentIDLT applies the LT predicate on the "provider_agent_id" field.
func ProviderAgentIDLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldProviderAgentID, v))
}

// ProviderAgentIDLTE applies the LTE predicate on the "provider_agent_id" field.
func ProviderAgentIDLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldProviderAgentID, v))
}

// ProviderAgentIDContains applies the Contains predicate on the "provider_agent_id" field.
func ProviderAgentIDContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldProviderAgentID, v))
}

// ProviderAgentIDHasPrefix applies the HasPrefix predicate on the "provider_agent_id" field.
func ProviderAgentIDHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldProviderAgentID, v))
}

// ProviderAgentIDHasSuffix applies the HasSuffix predicate on the "provider_agent_id" field.
func ProviderAgentIDHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldProviderAgentID, v))
}

// ProviderAgentIDIsNil applies the IsNil predicate on the "provider_agent_id" field.
func ProviderAgentIDIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldProviderAgentID))
}

// ProviderAgentIDNotNil applies the NotNil predicate on the "provider_agent_id" field.
func ProviderAgentIDNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldProviderAgentID))
}

// ProviderAgentIDEqualFold applies the EqualFold predicate on the "provider_agent_id" field.
func ProviderAgentIDEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldProviderAgentID, v))
}

// ProviderAgentIDContainsFold applies the ContainsFold predicate on the "provider_agent_id" field.
func ProviderAgentIDContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldProviderAgentID, v))
}

// ProviderFunctionNameEQ applies the EQ predicate on the "provider_function_name" field.
func ProviderFunctionNameEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldProviderFunctionName, v))
}

// ProviderFunctionNameNEQ applies the NEQ predicate on the "provider_function_name" field.
func ProviderFunctionNameNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldProviderFunctionName, v))
}

// ProviderFunctionNameIn applies the In predicate on the "provider_function_name" field.
func ProviderFunctionNameIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldProviderFunctionName, vs...))
}

// ProviderFunctionNameNotIn applies the NotIn predicate on the "provider_function_name" field.
func ProviderFunctionNameNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldProviderFunctionName, vs...))
}

// ProviderFunctionNameGT applies the GT predicate on the "provider_function_name" field.
func ProviderFunctionNameGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldProviderFunctionName, v))
}

// ProviderFunctionNameGTE applies the GTE predicate on the "provider_function_name" field.
func ProviderFunctionNameGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldProviderFunctionName, v))
}

// ProviderFunctionNameLT applies the LT predicate on the "provider_function_name" field.
func ProviderFunctionNameLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldProviderFunctionName, v))
}

// ProviderFunctionNameLTE applies the LTE predicate on the "provider_function_name" field.
func ProviderFunctionNameLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldProviderFunctionName, v))
}

// ProviderFunctionNameContains applies the Contains predicate on the "provider_function_name" field.
func ProviderFunctionNameContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldProviderFunctionName, v))
}

// ProviderFunctionNameHasPrefix applies the HasPrefix predicate on the "provider_function_name" field.
func ProviderFunctionNameHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldProviderFunctionName, v))
}

// ProviderFunctionNameHasSuffix applies the HasSuffix predicate on the "provider_function_name" field.
func ProviderFunctionNameHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldProviderFunctionName, v))
}

// ProviderFunctionNameIsNil applies the IsNil predicate on the "provider_function_name" field.
func ProviderFunctionNameIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldProviderFunctionName))
}

// ProviderFunctionNameNotNil applies the NotNil predicate on the "provider_function_name" field.
func ProviderFunctionNameNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldProviderFunctionName))
}

// ProviderFunctionNameEqualFold applies the EqualFold predicate on the "provider_function_name" field.
func ProviderFunctionNameEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldProviderFunctionName, v))
}

// ProviderFunctionNameContainsFold applies the ContainsFold predicate on the "provider_function_name" field.
func ProviderFunctionNameContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldProviderFunctionName, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointIsNil applies the IsNil predicate on the "endpoint" field.
func EndpointIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldEndpoint))
}

// EndpointNotNil applies the NotNil predicate on the "endpoint" field.
func EndpointNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldEndpoint))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldContainsFold(FieldEndpoint, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldStatus, vs...))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotNull(FieldResolvedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasConsumerAgent applies the HasEdge predicate on the "consumer_agent" edge.
func HasConsumerAgent() predicate.DependencyResolution {
	return predicate.DependencyResolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConsumerAgentTable, ConsumerAgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConsumerAgentWith applies the HasEdge predicate on the "consumer_agent" edge with a given conditions (other predicates).
func HasConsumerAgentWith(preds ...predicate.Agent) predicate.DependencyResolution {
	return predicate.DependencyResolution(func(s *sql.Selector) {
		step := newConsumerAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderAgent applies the HasEdge predicate on the "provider_agent" edge.
func HasProviderAgent() predicate.DependencyResolution {
	return predicate.DependencyResolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProviderAgentTable, ProviderAgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderAgentWith applies the HasEdge predicate on the "provider_agent" edge with a given conditions (other predicates).
func HasProviderAgentWith(preds ...predicate.Agent) predicate.DependencyResolution {
	return predicate.DependencyResolution(func(s *sql.Selector) {
		step := newProviderAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DependencyResolution) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DependencyResolution) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DependencyResolution) predicate.DependencyResolution {
	return predicate.DependencyResolution(sql.NotPredicates(p))
}
