apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-mesh-postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-mesh-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mcp-mesh-postgres.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-mesh-postgres.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-mesh-postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mcp-mesh-postgres.selectorLabels" . | nindent 4 }}
