// Code generated by ent, DO NOT EDIT.

package schemaentry

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schemaentry type in the database.
	Label = "schema_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldCanonical holds the string denoting the canonical field in the database.
	FieldCanonical = "canonical"
	// FieldRuntimeOrigin holds the string denoting the runtime_origin field in the database.
	FieldRuntimeOrigin = "runtime_origin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the schemaentry in the database.
	Table = "schema_entries"
)

// Columns holds all SQL columns for schemaentry fields.
var Columns = []string{
	FieldID,
	FieldHash,
	FieldCanonical,
	FieldRuntimeOrigin,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// RuntimeOrigin defines the type for the "runtime_origin" enum field.
type RuntimeOrigin string

// RuntimeOriginUnknown is the default value of the RuntimeOrigin enum.
const DefaultRuntimeOrigin = RuntimeOriginUnknown

// RuntimeOrigin values.
const (
	RuntimeOriginPython     RuntimeOrigin = "python"
	RuntimeOriginTypescript RuntimeOrigin = "typescript"
	RuntimeOriginJava       RuntimeOrigin = "java"
	RuntimeOriginUnknown    RuntimeOrigin = "unknown"
)

func (ro RuntimeOrigin) String() string {
	return string(ro)
}

// RuntimeOriginValidator is a validator for the "runtime_origin" field enum values. It is called by the builders before save.
func RuntimeOriginValidator(ro RuntimeOrigin) error {
	switch ro {
	case RuntimeOriginPython, RuntimeOriginTypescript, RuntimeOriginJava, RuntimeOriginUnknown:
		return nil
	default:
		return fmt.Errorf("schemaentry: invalid enum value for runtime_origin field: %q", ro)
	}
}

// OrderOption defines the ordering options for the SchemaEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByRuntimeOrigin orders the results by the runtime_origin field.
func ByRuntimeOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeOrigin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
