# Role for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-mesh-registry-leader-election
  namespace: mcp-mesh
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# RoleBinding for leader election
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-mesh-registry-leader-election
  namespace: mcp-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-mesh-registry-leader-election
subjects:
  - kind: ServiceAccount
    name: mcp-mesh-registry
    namespace: mcp-mesh
