apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-agent
  namespace: mcp-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-agent
  template:
    metadata:
      labels:
        app: hello-agent
    spec:
      containers:
        - name: agent
          image: localhost:5000/mcp-mesh-agent:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: AGENT_NAME
              value: "hello-agent"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MCP_MESH_REGISTRY_URL
              value: "http://mcp-mesh-registry:8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-agent
  namespace: mcp-mesh
spec:
  selector:
    app: hello-agent
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
