apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-mesh

resources:
  # Namespace and CRDs first
  - namespace.yaml
  - crds/mcpagent-crd.yaml

  # Foundation services - PostgreSQL, Redis, Tempo (registry dependencies)
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - redis/redis-deployment.yaml
  - observability/tempo/configmap.yaml
  - observability/tempo/pvc.yaml
  - observability/tempo/deployment.yaml
  - observability/tempo/service.yaml

  # Registry (depends on PostgreSQL, Redis, Tempo)
  - registry/configmap.yaml
  - registry/secret.yaml
  - registry/serviceaccount.yaml
  - registry/rbac.yaml
  - registry/service.yaml
  - registry/deployment.yaml
  - registry/backup-cronjob.yaml

  # Observability - Grafana (depends on registry for metrics)
  - observability/grafana/configmap.yaml
  - observability/grafana/pvc.yaml
  - observability/grafana/deployment.yaml
  - observability/grafana/service.yaml

  # Agents (depend on registry for discovery)
  - agents/configmap.yaml
  - agents/agent-code-configmap.yaml
  - agents/secret.yaml
  - agents/hello-world-deployment.yaml
  - agents/system-agent-deployment.yaml
  - agents/fastmcp-agent-deployment.yaml
  - agents/enhanced-fastmcp-agent-deployment.yaml
  - agents/dependent-agent-deployment.yaml

  # Ingress (last, depends on all services)
  - ingress-hosts.yaml
  - ingress-path.yaml

commonLabels:
  app.kubernetes.io/part-of: mcp-mesh
  app.kubernetes.io/managed-by: kustomize
