apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-mesh

resources:
  - namespace.yaml
  - crds/mcpagent-crd.yaml
  # PostgreSQL database
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  # Registry
  - registry/configmap.yaml
  - registry/secret.yaml
  - registry/serviceaccount.yaml
  - registry/rbac.yaml
  - registry/service.yaml
  - registry/service-headless.yaml
  - registry/statefulset.yaml
  - registry/pvc.yaml
  - registry/backup-cronjob.yaml
  # Redis for session storage (Phase 6+)
  - redis/redis-deployment.yaml
  # Agents
  - agents/configmap.yaml
  - agents/agent-code-configmap.yaml
  - agents/secret.yaml
  - agents/hello-world-deployment.yaml
  - agents/system-agent-deployment.yaml
  - agents/fastmcp-agent-deployment.yaml
  - agents/enhanced-fastmcp-agent-deployment.yaml
  - agents/dependent-agent-deployment.yaml
  # Ingress
  - ingress-hosts.yaml
  - ingress-path.yaml

commonLabels:
  app.kubernetes.io/part-of: mcp-mesh
  app.kubernetes.io/managed-by: kustomize
