apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: mcp-mesh
  labels:
    app: tempo
    component: observability
spec:
  type: ClusterIP
  ports:
  - port: 3200
    targetPort: 3200
    protocol: TCP
    name: http
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: grpc
  selector:
    app: tempo