# MCP Mesh Documentation Site Configuration

# Site settings
title: MCP Mesh
description: Enterprise-grade distributed service mesh for MCP agents. Kubernetes-native platform with zero-boilerplate dependency injection.
url: https://dhyansraj.github.io
baseurl: /mcp-mesh

# Theme
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO and metadata
author: MCP Mesh Contributors
twitter:
  username: # Add your Twitter handle if you have one
  card: summary_large_image

logo: # Add path to logo if you have one

# Social links
github_username: dhyansraj
repository: dhyansraj/mcp-mesh

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /01-getting-started
  - title: Documentation
    url: /mesh-decorators
  - title: GitHub
    url: https://github.com/dhyansraj/mcp-mesh

# Exclude from processing
exclude:
  - .nojekyll
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  parse_block_html: true
  
# Liquid settings - prevent processing in code blocks
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Permalink style
permalink: pretty

# Enable GitHub metadata
github: [metadata]
