apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-mesh

resources:
  - namespace.yaml
  - crds/mcpagent-crd.yaml
  # PostgreSQL database
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  # Registry
  - registry/configmap.yaml
  - registry/secret.yaml
  - registry/serviceaccount.yaml
  - registry/rbac.yaml
  - registry/service.yaml
  - registry/service-headless.yaml
  - registry/statefulset.yaml
  - registry/pvc.yaml
  - registry/backup-cronjob.yaml
  # Agents - base configuration only, no specific deployments
  - agents/configmap.yaml
  - agents/secret.yaml
  # Observability
  - observability/grafana/configmap.yaml
  - observability/grafana/pvc.yaml
  - observability/grafana/deployment.yaml
  - observability/grafana/service.yaml
  - observability/tempo/configmap.yaml
  - observability/tempo/pvc.yaml
  - observability/tempo/deployment.yaml
  - observability/tempo/service.yaml

commonLabels:
  app.kubernetes.io/part-of: mcp-mesh
  app.kubernetes.io/managed-by: kustomize

# ConfigMap generators for custom agents
# Users can add their own agent configs here
configMapGenerator: []

# Secret generators for sensitive data
secretGenerator: []
